realm/realm-kotlin

- examples/kmm-sample/androidApp/build.gradle.kts
- examples/kmm-sample/androidApp/src/main/res/layout/activity_main.xml
- examples/kmm-sample/build.gradle.kts
- examples/kmm-sample/settings.gradle.kts
- examples/kmm-sample/shared/build.gradle.kts
This updates the sample project to use our snapshots from OJO. Due to the marker artifacts not being published (#100) we have to apply our plugin the old way. 
Closes #74
> Consume public artifacts in sample projects

- Jenkinsfile
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/Config.kt
- buildSrc/src/main/kotlin/io/realm/RealmPublishPlugin.kt
- packages/cinterop/build.gradle.kts
- packages/gradle-plugin/build.gradle.kts
- packages/jni-swig-stub/build.gradle.kts
- packages/library/build.gradle.kts
- packages/plugin-compiler-shaded/build.gradle.kts
- packages/plugin-compiler/build.gradle.kts
- packages/runtime-api/build.gradle.kts
Using https://www.jfrog.com/confluence/display/JFROG/Gradle+Artifactory+Plugin somehow renders stale files or metadata for `cinterop-...-cinterop-realm_wrapper.klib` and `cinterop-...-sources.jar` files. The files are correct on first release, but on subsequent SNAPSHOT releases the files will not be uploaded or they are uploaded in place of the previous release's files. 
Using plain `maven-plugin` repository fixes the issue.
> Publish to OJO using maven publish plugin

- packages/cinterop/src/androidTest/java/io/realm/interop/CinteropTest.kt
- packages/cinterop/src/darwinCommon/kotlin/io/realm/interop/RealmInterop.kt
- packages/cinterop/src/darwinTest/kotlin/io/realm/CinteropTest.kt
- packages/cinterop/src/jvmCommon/kotlin/io/realm/interop/RealmInterop.kt
- packages/cinterop/src/nativeCommon/realm.def
- packages/jni-swig-stub/build.gradle.kts
- packages/jni-swig-stub/realm.i
- packages/runtime-api/src/commonMain/kotlin/io/realm/runtimeapi/Link.kt
This updates to the latest C-API with update API (`realm_string_t`->`const char*` and plain typedefs for key types).
> Update type handling according to new C-API

- Jenkinsfile
- examples/kmm-sample/androidApp/build.gradle.kts
Fixes #139 
now CI could fail with the following error after running monkey
```
47 actionable tasks: 47 executed
+ /Users/realm/Library/Android/sdk//platform-tools/adb shell monkey -p io.realm.example.kmmsample.androidApp -v 500 --kill-process-after-error
bash arg: -p
bash arg: io.realm.example.kmmsample.androidApp
bash arg: -v
bash arg: 500
bash arg: --kill-process-after-error
args: [-p, io.realm.example.kmmsample.androidApp, -v, 500, --kill-process-after-error]
arg: "-p"
arg: "io.realm.example.kmmsample.androidApp"
arg: "-v"
arg: "500"
arg: "--kill-process-after-error"
data="io.realm.example.kmmsample.androidApp"
:Monkey: seed=1615604288075 count=500
:AllowPackage: io.realm.example.kmmsample.androidApp
:IncludeCategory: android.intent.category.LAUNCHER
:IncludeCategory: …
```
> Add step to run monkey on sample app

- README.md
Calling `./gradlew assemble` from test results in 
```
> Task :compileKotlinJvm FAILED
e: java.lang.IllegalStateException: Cannot find io.realm.interop.RealmModelInternal on platform JVM (JVM_1_8).
```
Compiling `packages` and running the test targets like CI does works fine
> Update "How to build" instructions.

- .gitmodules
- packages/cinterop/build.gradle.kts
- packages/cinterop/src/jvmCommon/CMakeLists.txt
- packages/jni-swig-stub/build.gradle.kts
This moves the `external` folder to `packages` as it is really annoying to navigate to the sources outside of the actual project
> Move external sources to packages folder

- Jenkinsfile
The Gradle cache is re-used between stages, but due to how the script was currently structured, it was possible for builds to interleave between stages. If PR's interleaved this way, it could leave the Gradle cache in an undefined state resulting in obscure crashes. This PR changes this, so we grab a global lock for the entire build, meaning that only one build at a time can access the Gradle cache.
> Add global lock to JenkinsFile

- Jenkinsfile
This adds a 2-hour timeout to CI jobs. The activity flags mean the timeout is counted from the last activity in the logs instead of total duration. This seems to be match closer what we are after and we don't have any tests or otherwise that risk going into a loop and logging things at the same time.
> Add timeout to CI jobs

- examples/kmm-sample/androidApp/build.gradle.kts
- examples/kmm-sample/build.gradle.kts
- examples/kmm-sample/shared/build.gradle.kts
The sample project cannot even initialize in the IDE when trying to resolve the snapshot version defined in `Config.kt`. Hardcode the sample to use the latest released version until settling on the correct setup.
> Fix kmm-sample to use version 0.1.0

- packages/library/src/androidMain/kotlin/io/realm/internal/PlatformHelper.kt
- packages/library/src/commonMain/kotlin/io/realm/Realm.kt
- packages/library/src/commonMain/kotlin/io/realm/internal/PlatformHelper.kt
- packages/library/src/darwinCommon/kotlin/io.realm.internal/PlatformHelper.kt
- packages/library/src/jvmMain/kotlin/io/realm/internal/PlatformHelper.kt
- packages/library/src/macosMain/kotlin/io/realm/internal/PlatformHelper.kt
- test/build.gradle.kts
- test/src/androidMain/kotlin/io/realm/util/PlatformUtils.kt
- test/src/androidTest/kotlin/io/realm/MemoryTests.kt
- test/src/androidTest/kotlin/io/realm/shared/NotificationTests.kt
- test/src/androidTest/kotlin/io/realm/shared/RealmTests.kt
- test/src/commonMain/kotlin/io/realm/util/Utils.kt
- test/src/jvmMain/kotlin/io/realm/util/PlatformUtils.kt
- test/src/macosMain/kotlin/io/realm/util/PlatformUtils.kt
- test/src/macosTest/kotlin/io/realm/MemoryTests.kt
This makes the `Realm` frozen and tracks all intermediate frozen realm references and closes them when the realm is closed.
> Track and close intermediate realm references

- CHANGELOG.md
- packages/cinterop/src/commonMain/kotlin/io/realm/interop/RealmInterop.kt
- packages/cinterop/src/darwinCommon/kotlin/io/realm/interop/RealmInterop.kt
- packages/cinterop/src/jvmCommon/kotlin/io/realm/interop/RealmInterop.kt
- packages/library/src/commonMain/kotlin/io/realm/MutableRealm.kt
- packages/library/src/commonMain/kotlin/io/realm/internal/RealmObjectHelper.kt
- packages/library/src/commonMain/kotlin/io/realm/internal/RealmObjectInternal.kt
- packages/library/src/commonMain/kotlin/io/realm/internal/RealmObjectUtil.kt
- test/src/androidTest/kotlin/io/realm/shared/MutableRealmTests.kt
- test/src/commonMain/kotlin/test/StringPropertyWithPrimaryKey.kt
Add method to retrieve latest version of a frozen inside a write transaction. 
```
class MutableRealm : BaseRealm {
/**
* Get latest version of an object.
*
* Realm write transactions always operate on the latest version of data. This method
* makes it possible to easily find the latest version of any frozen Realm Object and
* return a copy of it that can be modified while inside the write block.
*
* *Note:* This object is not readable outside the write block unless it has been explicitly
* returned from the write.
*
* @param obj Realm object to look up. Its latest state will be returned. If the object
* has been deleted, `null` will be returned.
*/
public fun <T : RealmObject> findLatest(obj: T?): T?
}
```
FIXMEs:
> Add findLatest to resolve latest version of frozen object

- README.md
- update "realm-kotlin" plugin name to "io.realm.kotlin"
- remove redundant screenshots
- remove explicit version references, replace with `<VERSION>` placeholder
- point users to config/github releases section for potential version values
- updated all transaction usages to the `write`/`writeBlocking` syntax from the now-removed `beginTransaction`/`commitTransaction` pattern
- removed usages of the `realm.create` method, which has been deprecated
- updated `maven(url = "https://oss.jfrog.org/artifactory/oss-snapshot-local")` dependency references to `mavenCentral()`, since that's a default KMM template setting that most users will understand that they don't need to change.
> Fix README installation instructions

- CHANGELOG.md
- buildSrc/src/main/kotlin/Config.kt
- packages/cinterop/build.gradle.kts
When releasing darwing artifacts the default build type was set to `debug` 
Setting the default to `Release` will allow uploading the stripped KLIB instead
> KLIB release build type as default

- packages/library/build.gradle.kts
(so we can direct link to classes across SDK releases -- versions are already handled in the base path)
> Remove version from path of API reference links

- packages/library/build.gradle.kts
Setting `isMinified = true` for a library project https://github.com/realm/realm-kotlin/blob/master/packages/library/build.gradle.kts#L96  doesn't make sense (since it will remove all entries for release when producing the AAR). 
With this fix the `Release` variant for Android is working again.
> Remove minifying from the library

- CHANGELOG.md
- packages/library/src/commonMain/kotlin/io/realm/internal/RealmUtils.kt
- test/src/androidTest/kotlin/io/realm/shared/RealmListTests.kt
- test/src/commonMain/kotlin/test/list/RealmListContainer.kt
Closes https://github.com/realm/realm-kotlin/issues/334.
Fixed bug that prevented us from storing prepopulated lists (whether of primitive type or objects) using `copyToRealm`.
> RealmList - copyToRealm with prepopulated lists

- Jenkinsfile
Turns out that the way we found the version name was too relaxed and broke when adding an unrelated comment in the file.
Run that verifies this works here: https://ci.realm.io/job/realm/job/realm-kotlin/job/master/123/console (check console logs)
> Fix releasing SNAPSHOTs 

- packages/library/build.gradle.kts
- packages/library/io.realm.md
- packages/library/overview.md
- packages/library/src/commonMain/kotlin/io/realm/BaseRealm.kt
- packages/library/src/commonMain/kotlin/io/realm/Callback.kt
- packages/library/src/commonMain/kotlin/io/realm/Cancellable.kt
- packages/library/src/commonMain/kotlin/io/realm/MutableRealm.kt
- packages/library/src/commonMain/kotlin/io/realm/PrimaryKey.kt
- packages/library/src/commonMain/kotlin/io/realm/Queryable.kt
- packages/library/src/commonMain/kotlin/io/realm/Realm.kt
- packages/library/src/commonMain/kotlin/io/realm/RealmConfiguration.kt
- packages/library/src/commonMain/kotlin/io/realm/RealmObject.kt
- packages/library/src/commonMain/kotlin/io/realm/RealmResults.kt
- packages/library/src/commonMain/kotlin/io/realm/VersionId.kt
- packages/library/src/commonMain/kotlin/io/realm/info.md
- packages/library/src/commonMain/kotlin/io/realm/log/LogLevel.kt
- packages/library/src/commonMain/kotlin/io/realm/log/RealmLogger.kt
- packages/library/src/commonMain/kotlin/io/realm/log/info.md
- test/src/androidTest/kotlin/io/realm/shared/RealmTests.kt
Cleaned up package info (#318) and first line doc for classes (#317). 
Still lacking overall descriptive content for `io.realm` and especially `Realm`.
Questions
> Dokka cleanups

- packages/library/src/commonMain/kotlin/io/realm/internal/SuspendableNotifier.kt
Log message on native introduced in #345 seems to be because the flow cannot deliver events unless `extraBufferCapacity ` is more than 0. Have to investigate why this is the case, but setting to 1 eliminates the error.
> Fix realm changed notification on native.

- CHANGELOG.md
- buildSrc/src/main/kotlin/Config.kt
Kotlin 1.5.20 causing some incompatibility issues with the Bookshelf app 
```
e: Could not find "/Users/nabil/.gradle/caches/modules-2/files-2.1/io.realm.kotlin/library-iosx64/0.45.0-SNAPSHOT/9f6174f4f610fd23472aa2f0e2d9879584c9ecb5/library.klib" in [/Users/nabil/Dev/realm/KMP/master-2/realm-kotlin-samples/Bookshelf, /Users/nabil/.konan/klib, /Users/nabil/.konan/kotlin-native-prebuilt-macos-1.5.10/klib/common, /Users/nabil/.konan/kotlin-native-prebuilt-macos-1.5.10/klib/platform/ios_x64]
The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=9ff73205-f03d-4bcd-99a6-25f7b424d5f7, currentDir=/Users/nabil/Dev/realm/KMP/master-2/realm-kotlin-samples/Bookshelf}
Attempting to read last messages from the daemon log...
Daemon pid: 47119
log …
```
> Revert to Kotlin 1.5.10

- CHANGELOG.md
- packages/build.gradle.kts
- packages/cinterop/src/commonMain/kotlin/io/realm/interop/RealmInterop.kt
- packages/cinterop/src/darwinCommon/kotlin/io/realm/interop/RealmInterop.kt
- packages/cinterop/src/jvmCommon/kotlin/io/realm/interop/RealmInterop.kt
- packages/cinterop/src/nativeCommon/realm.def
- packages/library/src/commonMain/kotlin/io/realm/MutableRealm.kt
- packages/library/src/commonMain/kotlin/io/realm/internal/RealmUtils.kt
- test/src/androidTest/kotlin/io/realm/shared/PrimaryKeyTests.kt
This is adding a manual check for conflicting primary keys before adding new objects. 
Closes #192
> Throw errors when importing objects with duplicate primary keys

- README.md
- test/src/macosTest/kotlin/io/realm/shared
- test/src/macosTest/kotlin/io/realm/shared/ImportTests.kt
- test/src/macosTest/kotlin/io/realm/shared/LinkTests.kt
- test/src/macosTest/kotlin/io/realm/shared/LogTests.kt
- test/src/macosTest/kotlin/io/realm/shared/MigrationTests.kt
- test/src/macosTest/kotlin/io/realm/shared/ModuleTest.kt
- test/src/macosTest/kotlin/io/realm/shared/MutableRealmTests.kt
- test/src/macosTest/kotlin/io/realm/shared/NullabilityTests.kt
- test/src/macosTest/kotlin/io/realm/shared/PrimaryKeyTests.kt
- test/src/macosTest/kotlin/io/realm/shared/RealmConfigurationTests.kt
- test/src/macosTest/kotlin/io/realm/shared/RealmListTests.kt
- test/src/macosTest/kotlin/io/realm/shared/RealmObjectTests.kt
- test/src/macosTest/kotlin/io/realm/shared/RealmResultsTests.kt
- test/src/macosTest/kotlin/io/realm/shared/RealmTests.kt
- test/src/macosTest/kotlin/io/realm/shared/SampleTests.kt
- test/src/macosTest/kotlin/io/realm/shared/SchemaTests.kt
- test/src/macosTest/kotlin/io/realm/shared/VersionIdTests.kt
- test/src/macosTest/kotlin/io/realm/shared/notifications
Symlink the shared platform test folder instead of individual tests.
> Linked shared test folder instead of files

- Jenkinsfile
- test/sync/src/androidTest/kotlin/io/realm/test/mongodb/shared/AppTests.kt
This PR starts the Docker container on Jenkins that contains the MongoDB Test Server and run Sync integration tests on it.
> Add support for running Sync Integration Tests

- Jenkinsfile
- packages/cinterop/build.gradle.kts
Closes #454 
This PR does two things:
- Enable CCache support
- Don't wipe the workspace between PR builds .These options clear all files not part of the repo, including those in `.gitignore`. In our case, this specifically means any `.gradle` or `.cxx` caches already built.
By keeping those around, we can significantly increase build times for PR's, but it relies on the build script being able to handle incremental builds. Some changes needed for this were added in #452 (zip file handling), so this PR will fail until that PR is merged.
With multiple nodes also present, I had to refactor how we do locking. Turns out that locking on a node is rather difficult, but fortunately doesn't seem needed either. But I did had to refactor the pipeline to make sure that all steps run on the same …
> Enable incremental builds on CI

- packages/library-sync/src/commonMain/kotlin/io/realm/mongodb/App.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/mongodb/internal/AppImpl.kt
- test/sync/src/androidTest/kotlin/io/realm/test/mongodb/shared/AppTests.kt
Error handling in sync calls would follow the standard error catching. This PR reverts from using `Result` to throwing exceptions.
Users can at any moment wrap the calls with `runCatching` to convert the data/exceptions in a `Result` instance.
> Revert using Result as transport for resulting data on sync calls

- packages/cinterop/src/commonMain/kotlin/io/realm/mongodb/AppException.kt
- packages/cinterop/src/commonMain/kotlin/io/realm/mongodb/Errors.kt
- packages/cinterop/src/darwin/kotlin/io/realm/internal/interop/RealmInterop.kt
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
- test/sync/src/androidTest/kotlin/io/realm/test/mongodb/shared/AppTests.kt
This PR introduces the AppException as the exception thrown by sync methods.
It is not fully implemented and it requires it to implement the full sync error hierarchy.
> Sync login method to throw AppException instead of RuntimeException

- packages/cinterop/src/darwin/kotlin/io/realm/internal/interop/RealmInterop.kt
- packages/cinterop/src/jvm/kotlin/io/realm/internal/interop/RealmInterop.kt
It allows the sync client to dynamically change the host.
> Enable sync client metadata as plain text

- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmImpl.kt
- packages/library-base/src/commonMain/kotlin/io/realm/internal/SuspendableWriter.kt
- test/base/src/androidTest/kotlin/io/realm/test/shared/MutableRealmTests.kt
- test/base/src/androidTest/kotlin/io/realm/test/shared/RealmTests.kt
> Aligning realm references from writer results and public realm

- test/base/src/androidTest/kotlin/io/realm/test/shared/RealmTests.kt
Failing test in https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/master/186/pipeline/ is actually a valid actual outcome as intermediate references could be cleared if the GC kicks in before doing the write, thus ignoring until we have a deterministic way of verifying clean up of versions.
> Ignore nondeterministic native GC test

- Jenkinsfile
- packages/cinterop/src/jvm/CMakeLists.txt
- packages/cinterop/src/jvmMain/CMakeLists.txt
- packages/cinterop/src/jvmMain/linux/CMakeLists.txt
- packages/cinterop/src/jvmMain/windows/CMakeLists.txt
- packages/jni-swig-stub/.gitignore
- packages/jni-swig-stub/build.gradle.kts
This just puts all swig-generated content into `jni-swig-stub/build/generated/sources/{jni,java}` and adds appropriate incremental build dependencies to input files.
> Separating generated swig code from manual code

- packages/library-sync/src/commonMain/kotlin/io/realm/mongodb/AppConfiguration.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/mongodb/internal/AppConfigurationImpl.kt
This just injecst the `NetworkTransport` instead of constructing it internally in `AppConfigurationImpl`. 
This allows us to mock the `NetworkTransport` of `AppConfigurationImpl` and also allows us to use the same logger for `AppConfiguration` and `KtorNetworkTransport`.
> Rework AppConfiguration initialization

- packages/library-base/build.gradle.kts
The task generating `SDK_VERSION`-constant wasn't triggered for Kotlin native compilation sets. 
Apparently the `org.jetbrains.kotlin.gradle.tasks.KotlinCompile` is only the JVM tasks, whereas `org.jetbrains.kotlin.gradle.dsl.KotlinCompile<*>` also covers native ones.
> Trigger sdk version generation for native targets too

- Jenkinsfile
- dependencies.list
- tools/sync_test_server/start_server.sh
This now requires globally available AWS credentials.
Also a small quality-of-life improvement for making it easier to manually wipe the workspace.
> Update to latest BAAS server

- CHANGELOG.md
- packages/cinterop/build.gradle.kts
- packages/library-base/build.gradle.kts
- Currently Ktor client libcurl engine is not released with support for M1 this is why this PR is limited to the non-sync variant
- Once we add support for non-sync, we should consider using the new build system https://github.com/realm/realm-kotlin/issues/141 as well as stop building Universal Mach-O archive by using `ARCHS` flag
Example:
Building for `arm64`
```
xcodebuild -sdk iphonesimulator -configuration Debug -target install ARCHS=arm64 -UseModernBuildSystem=NO
```
Building for `X64`
```
xcodebuild -sdk iphonesimulator -configuration Debug -target install ARCHS=x86_64 -UseModernBuildSystem=NO
```
The PR has been tested against `MultiplatformDemo` and `JVMConsole` on a M1 macmini
> Add M1 support for library-base

- packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmListInternal.kt
- test/base/src/androidTest/kotlin/io/realm/test/shared/RealmListTests.kt
The implementations for both JVM and native were not aligned - see https://youtrack.jetbrains.com/issue/KT-47211
This has been fixed so the manual check is no longer needed.
> Remove manual check from `addAll` with index in `RealmList`

- buildSrc/build.gradle.kts
- examples/kmm-sample/build.gradle.kts
- packages/build.gradle.kts
- packages/library-base/build.gradle.kts
- packages/library-sync/build.gradle.kts
- test/build.gradle.kts
Just replacing all `jcenter` references with `mavenCentral` as it seems all dependencies are not available here.
> Replace JCenter with Maven Central

- CHANGELOG.md
- packages/gradle-plugin/src/main/kotlin/io/realm/gradle/RealmAnalytics.kt
Fixes #626 
Added a quick fix that ensures no modifications to the configs are carried out while processing analytics in compile time.
This doesn't fix the issue per se but at least will give us time until we have a fix for https://github.com/realm/realm-kotlin/issues/498 which will likely solve the problem.
> Synchronously process project configurations to avoid exceptions when running parallel builds

- CHANGELOG.md
- buildSrc/src/main/kotlin/Config.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/compiler/AccessorModifierIrGeneration.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/compiler/IrUtils.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/compiler/Logger.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/compiler/RealmModelLoweringExtension.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/compiler/RealmModelSyntheticPropertiesGeneration.kt
- packages/plugin-compiler/src/test/kotlin/io/realm/compiler/GenerationExtensionTest.kt
- test/base/src/jvmTest/kotlin/io/realm/test/compiler/IndexTests.kt
- test/base/src/jvmTest/kotlin/io/realm/test/compiler/list/ListTests.kt
This adds context with clickable link for model definition errors that allows navigation to the exact location of the erroneous definition.
Further, separated all compiler plugin errors into a `fatalError` to be able to differentiate them from user modeling errors. 
Closes #173
> Link model definition errors to offending source code

- CHANGELOG.md
- buildSrc/src/main/kotlin/Config.kt
Looks like AGP 7.1.0 is finally GA 🥳
> Upgrade to AGP 7.1.0

- packages/library-base/src/commonMain/kotlin/io/realm/Configuration.kt
- packages/library-base/src/commonMain/kotlin/io/realm/internal/MutableRealmImpl.kt
- packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmListInternal.kt
- packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmObjectHelper.kt
- packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmObjectInternal.kt
- packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmReference.kt
- packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmUtils.kt
- packages/library-base/src/commonMain/kotlin/io/realm/internal/SuspendableNotifier.kt
- packages/library-base/src/commonMain/kotlin/io/realm/internal/query/ScalarQuery.kt
This PR reduces the amount of build warnings we have. This PR removes warnings found in `library-base`. Only two warnings should be left, which I'm not 100% sure what to do about:
```
w: Argument -module-name is passed multiple times. Only the last value will be used: io.realm.kotlin.library
w: /Users/cm/Realm/realm-kotlin/packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmObjectUtil.kt: (66, 52): Extension is shadowed by a member: public open fun freeze(frozenRealm: RealmReference): RealmObjectInternal?
```
> Remove build warnings

- CHANGELOG.md
- packages/plugin-compiler/src/main/kotlin/io/realm/compiler/AccessorModifierIrGeneration.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/compiler/RealmModelSyntheticPropertiesGeneration.kt
Some compiler API have changed in 1.6.20 (example https://github.com/realm/realm-kotlin/issues/619#issuecomment-1029962450) we can avoid bumping to `1.6.20` and still be compatible with `1.6.20` with the following refactors.
> Refactor the compiler plugin to avoid breaking API in 1.6.20

- CHANGELOG.md
- packages/cinterop/src/androidTest/java/io/realm/test/CinteropTest.kt
- packages/cinterop/src/commonMain/kotlin/io/realm/internal/interop/Errors.kt
- packages/cinterop/src/darwin/kotlin/io/realm/internal/interop/Errors.kt
- packages/cinterop/src/darwin/kotlin/io/realm/internal/interop/RealmInterop.kt
- packages/cinterop/src/darwinTest/kotlin/io/realm/test/CinteropTest.kt
- packages/cinterop/src/jvm/kotlin/io/realm/internal/interop/CoreErrorUtils.kt
- packages/cinterop/src/jvm/kotlin/io/realm/internal/interop/RealmInterop.kt
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
- packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmUtils.kt
I tried to eliminate our direct usage of the C++ core API #496, but we still don't have a way to do a real copy of the configuration and create a generic scheduler through the C-API. 
Closes #687
> Update to latest core scheduler API

- packages/library-base/proguard-rules-consumer-common.pro
Not 100% sure why this wasn't caught by our PR builds? 🤔
> Allow JVM lamdas and functional interfaces to be called from JNI

- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/MutableRealm.kt
- packages/library-base/src/commonMain/kotlin/io/realm/internal/MutableRealmImpl.kt
- test/base/src/androidTest/kotlin/io/realm/test/shared/MutableRealmTests.kt
Closes #616 
This throws better `IllegalArgumentException`'s for a number of cases when deleting objects in states that are not supported.
> Add better error messages when deleting unsupported objects.

- CONTRIBUTING.md
- README.md
Our README was getting a bit too large.
In order to improve readability, I reorganized into `README.md` and `CONTRIBUTING.md`, similar to how realm-core has done.
I also collapsed a few sections like examples/documentation, adjusted some references to docs and generally point people towards realm-kotlin-samples instead of the `kmm-sample` in this repo, since this is just for integration tests now.
I also moved the Beta notice to the top...but not 100% exactly what to write there.
I also removed the mention to our design documents. They did see a little bit of traffic, but not sure it is worth having references to them anymore since things quite a lot of things have changed. So I removed them to reduce the length of the doc.
> Reorganize and update README

- CHANGELOG.md
- packages/cinterop/src/jvm/CMakeLists.txt
- There's a difference of ~1MB on the overall AAR file when applying the linker `gc` flags
- `arm64` was `7.5MB` and now `7MB`
- This is also way below the size of a Java shared object with Sync which is around `9.2MB` for `arm64`
Most of the other flags set in Java are not necessary since they're set by the Android toolchain file
> Reducing binary size for Andorid dependency

- CHANGELOG.md
- packages/cinterop/build.gradle.kts
Previously ios simulator dependencies were built using a fat Mach-O binary containing [`x86_64`, `arm64` and `i386`] This causes issues when building a fat-framework for the following targets: `iosX64()`, `iosArm64()`, `iosSimulatorArm64()`  
```
> Task :shared:linkDebugFrameworkIosFat FAILED
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/nabil/Dev/realm/KMP/master-1/realm-kotlin-samples/Intro/shared/build/bin/iosX64/debugFramework/my_framework_static_new.framework/my_framework_static_new and /Users/nabil/Dev/realm/KMP/master-1/realm-kotlin-samples/Intro/shared/build/bin/iosArm64/debugFramework/my_framework_static_new.framework/my_framework_static_new have the same architectures (arm64) and can't be in the same fat output …
```
> Fix ios simulator static libraries 

- CHANGELOG.md
- packages/cinterop/src/commonMain/kotlin/io/realm/internal/interop/RealmInterop.kt
- packages/cinterop/src/darwin/kotlin/io/realm/internal/interop/RealmInterop.kt
- packages/cinterop/src/jvm/kotlin/io/realm/internal/interop/RealmInterop.kt
- packages/jni-swig-stub/realm.i
- packages/library-base/src/commonMain/kotlin/io/realm/internal/BaseRealmImpl.kt
- packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmImpl.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/mongodb/RealmExt.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/mongodb/internal/SyncedRealmContext.kt
- test/sync/src/androidTest/kotlin/io/realm/test/mongodb/shared/SyncSessionTests.kt
Closes #246 
This PR lays the groundwork for exposing sync functionality in the public API, starting with `Realm.syncSession`.
**API Notes**
- In Java we have a `Sync` class which basically just keep tracks of SyncSessions across thread-confined Realm instances and then offer the `reconnect()` method. Since the Realm instance is thread-safe in Kotlin, the need for such a class seems non-existent. So for now I don't think it is worth exposing it. We can offer the `reconnect()` method on the `SyncSession` directly. That it also reconnects all other sessions is just a side-effect that should be okay.
**Some design notes:**
- I kept `Realm.open` as is and then lazily inject the `SyncedRealmContext` on first access. This has the drawback that all public API entry points must be accessed in a …
> Introduce SyncedRealmContext and expose Realm.syncSession

- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmReference.kt
- test/sync/src/androidTest/kotlin/io/realm/test/shared/SyncedRealmTests.kt
This PR ensures that we have a valid transaction on each frozen realm reference. Failing to have that could cause core to clean up the version and that would render us invalid to query, create objects, etc. from that specific version. 
Closes #683
> Ensure existence of valid transaction on frozen realm references

- test/base/src/commonMain/kotlin/io/realm/test/util/TestHelper.kt
- test/sync/src/androidTest/kotlin/io/realm/test/mongodb/shared/SyncConfigTests.kt
- test/sync/src/androidTest/kotlin/io/realm/test/mongodb/shared/SyncSessionTests.kt
- test/sync/src/androidTest/kotlin/io/realm/test/shared/SyncedRealmTests.kt
Re-using the same partition key between tests seems to cause issues in some cases. The root cause is unclear, but two hypothesizes  could either be that some tests doesn't clean up correctly in case of other failures or that the Randomizer sometimes reuse a value. 
To work around this, this PR creates separate partition values for all sync-related tests. This finding the root cause would be ideal, `master` is currently broken so fixing that has the highest priority.
> Don't share partition value between tests.

- CHANGELOG.md
- packages/cinterop/src/commonMain/kotlin/io/realm/internal/interop/RealmInterop.kt
- packages/cinterop/src/darwin/kotlin/io/realm/internal/interop/RealmInterop.kt
- packages/cinterop/src/jvm/kotlin/io/realm/internal/interop/RealmInterop.kt
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
- packages/library-sync/src/commonMain/kotlin/io/realm/mongodb/User.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/mongodb/internal/UserImpl.kt
- test/sync/src/androidTest/kotlin/io/realm/test/mongodb/shared/UserTests.kt
Closes #244
Added `User.remove()`. We decided not to implement `App.removeUser(user)` as we can grab users with `App.allUsers()` and delete them from there.
> Add support for `User.remove()`

- packages/cinterop/src/commonMain/kotlin/io/realm/internal/interop/sync/NetworkTransport.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/mongodb/internal/HttpClientCache.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/mongodb/internal/KtorNetworkTransport.kt
- packages/library-sync/src/iosMain/kotlin/io/realm/mongodb/internal/HttpClientCache.kt
- packages/library-sync/src/jvm/kotlin/io/realm/mongodb/internal/HttpClientCache.kt
- packages/library-sync/src/macosMain/kotlin/io/realm/mongodb/internal/HttpClientCache.kt
- test/sync/src/androidTest/kotlin/io/realm/test/mongodb/shared/internal/KtorNetworkTransportTest.kt
- test/sync/src/androidTest/kotlin/io/realm/test/shared/SyncedRealmTests.kt
- test/sync/src/commonMain/kotlin/io/realm/test/mongodb/TestApp.kt
- test/sync/src/commonMain/kotlin/io/realm/test/mongodb/util/AdminApi.kt
- test/sync/src/commonMain/kotlin/io/realm/test/mongodb/util/HttpClient.kt
Closes #814 
This PR introduces a `close()` method for the NetworkTransport. This allows us to close the underlying HttpEngine, which seems to be required on macOS, as creating many engines eventually causes requests to timeout. Probably because some underlying resources is shared and not closed correctly.
`TestApp` has been reworked to correctly close the engines it uses but it is not doing anything for the public API.
In the public API, the NetworkTransport is tied to `AppConfiguration` which is a problem since we cannot close it from the App/Realm instances as it might be shared between many Apps/Realms. We need to figure out a pattern that allows people to do this, perhaps by lazily creating the network transport when needed.
> Cleanup HttpEngine in tests

- CHANGELOG.md
- packages/cinterop/src/commonMain/kotlin/io/realm/internal/interop/Callback.kt
- packages/cinterop/src/commonMain/kotlin/io/realm/internal/interop/RealmInterop.kt
- packages/cinterop/src/darwin/kotlin/io/realm/internal/interop/RealmInterop.kt
- packages/cinterop/src/darwinTest/kotlin/io/realm/test/CinteropTest.kt
- packages/cinterop/src/jvm/kotlin/io/realm/internal/interop/RealmInterop.kt
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.h
- packages/library-base/src/commonMain/kotlin/io/realm/Configuration.kt
- packages/library-base/src/commonMain/kotlin/io/realm/Realm.kt
- packages/library-base/src/commonMain/kotlin/io/realm/RealmConfiguration.kt
- packages/library-base/src/commonMain/kotlin/io/realm/internal/ConfigurationImpl.kt
- packages/library-base/src/commonMain/kotlin/io/realm/internal/InternalConfiguration.kt
- packages/library-base/src/commonMain/kotlin/io/realm/internal/LiveRealm.kt
- packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmConfigurationImpl.kt
- packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmImpl.kt
- packages/library-base/src/commonMain/kotlin/io/realm/internal/dynamic/DynamicMutableRealmImpl.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/mongodb/sync/SyncConfiguration.kt
- test/base/src/androidTest/kotlin/io/realm/test/shared/InitialDataTests.kt
- test/base/src/commonMain/kotlin/io/realm/test/StandaloneDynamicMutableRealm.kt
- test/sync/src/androidTest/kotlin/io/realm/test/mongodb/shared/SyncConfigTests.kt
Closes https://github.com/realm/realm-kotlin/issues/302
Closes https://github.com/realm/realm-kotlin/issues/422
Add support Configuration.initialData(), which works for both RealmConfiguration and SyncConfiguration. Similar to how it works in Realm Java.
This also sets a pattern for adding other functionality required to run at startup, like `initialSubscriptions` which was the reason for adding this now.
**Alternative designs**
The current design extends `realm_open`, which works because a previous PR changed our native configs, so they are created just before being needed, thus ensuring they are tied to a single Realm.
At first, I did attempt a different approach where the `DataInitialization` callback was passed into `InternalConfiguration.createNativeConfiguration()`, but it just made …
> Add support for writing initial data when opening a Realm file.

- CHANGELOG.md
- buildSrc/src/main/kotlin/Config.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/compiler/RealmModelLoweringExtension.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/compiler/RealmModelSyntheticPropertiesGeneration.kt
The usage of `IrConstructorCallImpl` has changed in Kotlin 1.7.0-RC. To be compatible with the upcoming release we switch to using the `IrConstructorCallImpl.fromSymbolOwner` builder.
> Preparing the compiler plugin to be compatible with Kotlin 1.7.0-RC

- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SyncSessionTests.kt
Increases test timeout for `uploadAndDownloadChangesSuccessfully`, which sometimes seems to fail on macOS/iOS. While the 30-second timeout should be more than enough, sometimes it is not. The root cause for this is not fully understood, but could just be CI resources being constrained.
So for now, increase the timeout more and 🤞 it fixes it.
> Decrease posibility of test failing

- CHANGELOG.md
- packages/cinterop/build.gradle.kts
Samples build targeting Apple silicon fail to run because they cannot resolve a symbol from the [IntelRDFPMathLib20U2](https://github.com/realm/realm-core/tree/master/src/external/IntelRDFPMathLib20U2).
The issue is caused by a misconfiguration in the build command for the cinterop macos universal target.
> Fix missing symbol on Apple silicon prevents samples to run

- CHANGELOG.md
- packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/jni-swig-stub/realm.i
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.h
This PR add explicit copying of string data passed to `realm_value_t.string`, thus when the `realm_value_t` is managed by the cinterop layer.
Questions:
Closes #890
> Clean up strings stored in realm_value_t managed by the JVM-cinterop layer

- packages/cinterop/build.gradle.kts
This adds Core source code as input for the various `cinterop` native compilation tasks and. This should ensure that we rebuild the C-API when the core sources is updated.
> Add input dependencies to cinterop native tasks

- CHANGELOG.md
- packages/library-base/proguard-rules-consumer-common.pro
Running an app that uses sync in release mode produces the following crash:
```
2022-06-20 15:47:51.156 8259-8259/io.realm.example.kmmsample.androidApp E/REALM: /Users/eduardo.lopez/git/realm-kotlin/packages/cinterop/src/jvm/jni/java_method.cpp:33: [realm-core-12.1.0] Assertion failed: m_method_id != nullptr with (method_name, signature) =  ["sendRequest", "(Ljava/lang/String;Ljava/lang/String;Ljava/util/Map;Ljava/lang/String;Lio/realm/kotlin/internal/interop/sync/ResponseCallback;)V"]
<backtrace not supported on this platform>!!! IMPORTANT: Please report this at https://github.com/realm/realm-core/issues/new/choose
2022-06-20 15:47:51.156 8259-8259/io.realm.example.kmmsample.androidApp A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 8259 (mple.androidApp), pid 8259 …
```
> Added proguard exception for `ResponseCallback`

- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmObjectReference.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelLoweringExtension.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelSyntheticPropertiesGeneration.kt
- packages/plugin-compiler/src/test/resources/sample/expected/00_ValidateIrBeforeLowering.ir
- packages/plugin-compiler/src/test/resources/schema/expected/00_ValidateIrBeforeLowering.ir
Closes #901 
We did not set the correct generic argument for 
```
@Nullable
private RealmObjectReference<T> io_realm_kotlin_objectReference;
```
Inside model classes. This accidentally worked because the generic parameter is type-erased at runtime, but if other libraries like Android Hilt also attempted to introspect or work with the source code it would report errors like `bad class file: <xxx> undeclared type variable: T`
This PR changes the compiler plugin so we now use the model class as the generic argument:
```
@Nullable
private RealmObjectReference<Sample> io_realm_kotlin_objectReference;
```
The fix has been verified to fix the the repro case here: https://github.com/realm/realm-kotlin/issues/901#issuecomment-1160393534
> Fix Compiler Plugin not setting RealmObjectReference generic argument correctly

- dependencies.list
- test/base/build.gradle.kts
- test/base/src/commonTest/kotlin/io/realm/kotlin/test/NotificationTests.kt
- test/sync/build.gradle.kts
- tools/sync_test_server/Dockerfile
- tools/sync_test_server/Dockerfile.local
- tools/sync_test_server/bind_android_ports.sh
- tools/sync_test_server/mongodb-realm-command-server.js
- tools/sync_test_server/start_local_server.sh
- tools/sync_test_server/start_server.sh
- tools/sync_test_server/stop_local_server.sh
This PR attempts to allow building and running `library-base` tests on Apple silicon. `library-sync` are not yet available to be run natively on Apple silicon but they can be emulated with Rosetta.
Tests target is now selected automatically based on the local machine architecture.
Two new sync server scripts have been introduced: `start_local_server.sh` and `stop_local_server.sh` that allow running the baas server locally instead of doing it on a docker image. It is a temporary solution until we get ARM64 baas server images.
Rosetta can be enabled by setting `JAVA_HOME` to an Intel JDK, tested with `jdk-11.0.15`, and then running the sync macos sync tests.
> Support running tests on apple silicon

- CHANGELOG.md
- packages/cinterop/src/darwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/darwinTest/kotlin/io/realm/kotlin/test/CinteropTest.kt
- packages/cinterop/src/jvm/jni/utils.h
- packages/jni-swig-stub/realm.i
- test/base/src/androidTest/kotlin/io/realm/kotlin/test/shared/nonlatin/NonLatinTests.kt
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/nonlatin/NonLatinTests.kt
Attempting to reproduce https://github.com/realm/realm-kotlin/issues/895 and also verify that we correctly roundtrip special strings, especially on the JVM which uses modified UTF8.
*Update:* This PR was initially created to investigate #895, but since the tests revealed issues around handling of strings with null-characters and the original issue of #895 is now handled by #909, this PR is now only targeting issues with strings containing null-characters.
> Fix reading strings containing null-characters

- CHANGELOG.md
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/exceptions/ClientResetRequiredException.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/RealmSyncUtils.kt
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/shared/SyncedRealmTests.kt
- test/sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/util/AdminApi.kt
Continuation from https://github.com/realm/realm-kotlin/pull/909 pointing to `releases`.
Fixed logic that wrongly assumed a recovery path should always exist when processing sync errors.
See https://github.com/realm/realm-kotlin/pull/898#issuecomment-1166207478
Added test that triggers a "permission denied" error by modifying the server's sync configuration using the Admin API.
Modified the mapping of sync errors to include permission denied and mark it as an `UnrecoverableSyncException` for users to gracefully handle app restart.
Closes https://github.com/realm/realm-kotlin/issues/895
> SyncError - fix assumption that recovery path should always be present

- Jenkinsfile
Updated `REALM_S3_ACCESS_KEY` since it was already present in master but not in releases. This caused the upload debug symbols and documentation tasks to fail while releasing 1.0.1.
> Updated credentials key

- tools/sync_test_server/stop_local_server.sh
The baas local development server did not boot up correctly after being shut down manually. This PR attempts to fix the issue by removing the PID files during the shutdown process.
> Fix local baas server not shut properly

- CHANGELOG.md
- packages/cinterop/src/jvm/jni/java_class_global_def.hpp
- packages/jni-swig-stub/realm.i
- packages/library-base/proguard-rules-consumer-common.pro
Fix erroneous package reference in proguard consumer file and moves initialization of `CoreErrorUtils` java class reference to library initialization. 
Closes #942
> Fix erroneous package name in proguard consumer file

- CHANGELOG.md
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/darwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/User.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/UserImpl.kt
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/UserTests.kt
Closes #491 
API should be straightforward and follows how it is implemented in Swift.
> Add support for `User.delete()`.

- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/SuspendableWriter.kt
- test/base/src/androidTest/kotlin/io/realm/kotlin/test/shared/RealmTests.kt
- test/base/src/commonTest/kotlin/io/realm/kotlin/test/Utils.kt
Closes #965
We didn't correctly check if users tried to return deleted objects from a write, which caused a NullPointer when we tried to freeze an invalid object.
We basically have two choices on what to do here:
1) Allow sending back a deleted object without trying to freeze it.
2) Throw some error if it happens.
I opted for 2) as I cannot see any use case where sending back a deleted object would actually be the behavior wanted, but if someone feel that there is a use case, I'll be happy to change it.
Regarding the exception type, I was torn a bit between `IllegalArgument` and `IllegalState`, but opted for `IllegalState` as argument exceptions are usually only used for input to a public function. Again, this can probably be debated, so if anyone can come up with good arguments for …
> Throw proper exception when returning invalid RealmObject from write

- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/shared/SyncedRealmTests.kt
- test/sync/src/commonMain/kotlin/io/realm/kotlin/entities/sync/BinaryObject.kt
> Fix flaky test: `SyncedRealmTests.waitForInitialData_timeOut`

- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/shared/SyncedRealmTests.kt
Local schema checks are more restrictive than synced Realms, so all server-side fields must also be part of the schema or be removed through a migration.
> Fix test converting a partition-based Realm into a local Realm.

- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/SyncClientResetIntegrationJVMTests.kt
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/AppConfigurationTests.kt
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/AppTests.kt
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/CredentialsTests.kt
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/EmailPasswordAuthTests.kt
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/FlexibleSyncConfigurationTests.kt
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/FlexibleSyncIntegrationTests.kt
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/MutableSubscriptionSetTests.kt
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SubscriptionSetTests.kt
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SubscriptionTests.kt
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SyncClientResetIntegrationTests.kt
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SyncConfigTests.kt
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SyncSessionTests.kt
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/UserTests.kt
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/nonlatin/NonLatinTests.kt
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/shared/SyncedRealmTests.kt
- test/sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/TestApp.kt
- test/sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/util/AdminApi.kt
- test/sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/util/AppConfigs.kt
The current approach to sync tests is to share a common App and database on the server. It can present some issues as if a test case modifies the server configuration and fails to revert it, the following test cases might fail. In such cases, it would be almost impossible to know that the cause of that failing test is a wrong server configuration.
With this PR we introduce App sandboxing, each test would have its own App and database. In this way, all the changes to the Realm app would be isolated to the test execution and would be discarded afterward.
It is also a step towards being able to run tests in parallel.
> Sandbox server apps to each test case

- LICENSE
Legal has confirmed that the export compliance clause is not needed on an open source projects such as the Realm SDKs.
This PR replace the LICENSE file with a clean Apache 2 license, ie. no ToC and export compliance. This allows tools such as github to pick up the correct license.
> Remove export compliance from LICENSE

- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
- packages/library-base/src/darwin/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
- packages/library-base/src/jvm/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
- test/base/src/commonMain/kotlin/io/realm/kotlin/test/util/TypeDescriptor.kt
Pulling this change from https://github.com/realm/realm-kotlin/pull/782 into `master` to keep the PR smaller.
This PR just fixes a smaller annoyance that calling `./gradlew assemble` crashes in the test project.
> Fix assemble crashing in the test project

- Jenkinsfile
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/EmailPasswordAuthTests.kt
- test/sync/src/androidTest/kotlin/io/realm/kotlin/test/shared/SyncedRealmTests.kt
- test/sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/TestApp.kt
- test/sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/util/AdminApi.kt
- tools/sync_test_server/app_config_generator.sh
- tools/sync_test_server/app_template/auth_providers/local-userpass.json
- tools/sync_test_server/app_template/functions/canReadPartition/config.json
- tools/sync_test_server/app_template/functions/canReadPartition/source.js
- tools/sync_test_server/app_template/functions/canWritePartition/config.json
- tools/sync_test_server/app_template/functions/canWritePartition/source.js
- tools/sync_test_server/app_template/functions/confirmFunc/source.js
- tools/sync_test_server/mongodb-realm-command-server.js
- tools/sync_test_server/start_local_server.sh
- tools/sync_test_server/start_server.sh
In the past, we have seen quite a lot of flakiness in the EmailPasswordAuth tests. The root cause was never discovered. With the refactor to Ktor 2, we started to see them again. This PR refactors the tests, so instead of modifying the config of a single app, we now use different test apps.
This seems to fix the flakiness + has the advantage of improving the speed of running tests.
> Refactor EmailPassword Auth tests.

- .github/workflows/auto-merge-branches.yml
- .github/workflows/auto-merge-release-to-master.yml
This will automatically create PR's between branches we think should be in sync:
- `releases` -> `master`
- `master` -> `release/ktor2-support`
Example: https://github.com/realm/realm-kotlin/pull/1019
PR is red because I canceled the build on CI as it didn't need to run for this.
> Enable auto-merge between branches

- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/dynamic/DynamicMutableRealmImpl.kt
- packages/test-base/src/commonMain/kotlin/io/realm/kotlin/test/StandaloneDynamicMutableRealm.kt
This PR just contains some small convenience changes that fixes executing `./gradlew assemble` in `packages`
> Fix assemble task for packages

- CHANGELOG.md
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/log/RealmLogger.kt
When messages was logged with formatting arguments, it was erroneously passed a `null` argument, which triggered formatting even though it should. 
Closes #1034
> Fix error formatting for log entries without arguments

- CHANGELOG.md
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/Callback.kt
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/darwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/jvm/jni/java_class_global_def.hpp
- packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/jni-swig-stub/realm.i
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.h
- packages/library-base/proguard-rules-consumer-common.pro
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/ConfigurationImpl.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/InternalConfiguration.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmImpl.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SyncConfigurationImpl.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/sync/SyncConfiguration.kt
Closing #1046 
This has been verified to fix the difference reported in https://jira.mongodb.org/browse/HELP-37904.
There are some open questions about how to clean up threadsafe references. It looks like we might be leaking memory in the client reset tests.
> Use async open when opening partition-based Realms.

- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/MutableRealm.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/dynamic/DynamicMutableRealm.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/InternalMutableRealm.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/dynamic/DynamicMutableRealmImpl.kt
- packages/test-base/src/androidTest/kotlin/io/realm/kotlin/test/shared/MutableRealmTests.kt
- packages/test-base/src/androidTest/kotlin/io/realm/kotlin/test/shared/dynamic/DynamicMutableRealmTests.kt
Closes #574 and #573.
Adds functionality that allows a user to wipe their current realm by invoking deleteAll().
Adds functionality to delete all objects of a specified class with delete(classname) or delete(KClass).
> Add support for deleteAll()

- CHANGELOG.md
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SyncedRealmContext.kt
- packages/test-sync/src/androidTest/kotlin/io/realm/kotlin/test/shared/SyncedRealmTests.kt
Closes https://github.com/realm/realm-kotlin/issues/1068
Note, when creating this patch I discovered another bug: https://github.com/realm/realm-kotlin/issues/1070.
A test has been written that catch this but it is marked as `@Ignore` for now.
> Fix SyncSession crashing when accessed after receiving remote changes

- README.md
The readme contained only instructions on how to use SNAPSHOT version if Groovy for Gradle was being used. Since it's a KMM project, it makes sense to provide the Kotlin instructions as well.
> Add Gradle Kotlin instructions

- CHANGELOG.md
- packages/cinterop/src/androidTest/java/io/realm/kotlin/test/CinteropTest.kt
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/sync/ApiKeyWrapper.kt
- packages/cinterop/src/darwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/darwinTest/kotlin/io/realm/kotlin/test/CinteropTest.kt
- packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/jni-swig-stub/realm.i
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.h
- packages/library-sync/proguard-rules-consumer-common.pro
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/User.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/auth/ApiKey.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/auth/ApiKeyAuth.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/ApiKeyAuthImpl.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/UserImpl.kt
- packages/test-base/src/androidTest/kotlin/io/realm/kotlin/test/shared/ReadMeTests.kt
- packages/test-base/src/androidTest/kotlin/io/realm/kotlin/test/shared/migration/RealmMigrationTests.kt
- packages/test-sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/ApiKeyAuthTests.kt
- packages/test-sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/CredentialsTests.kt
Early version of #432, some optimisations still needs to be done, and discussions about error handling needs to be made as well.
This depends on us being able to merge changes from `jm/named-apikey-callbacks` in core.
need to update `CredentialsTests` and `CHANGELOG.md`
> Add support for ApiKeyAuthProvider

- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SyncedRealmTests.kt
The MutableRealmInt test was failing sporadically on CI due to the download sometimes not completing in time. Increasing the timeout should fix this.
> Increase test timeout

- CHANGELOG.md
- packages/library-base/proguard-rules-consumer-common.pro
Adds an entry for `NativePointer` into proguard. This a crash when performing a migration.
> Add missing proguard rules

- CHANGELOG.md
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/jni-swig-stub/realm.i
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/AppConfiguration.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/AppConfigurationImpl.kt
- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/AppConfigurationTests.kt
- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/AppTests.kt
Closes #413.
Users can encrypt user metadata via `AppConfiguration.Builder.encryptionKey()` and access their encryption key via `AppConfiguration.encryptionKey`.
> Add support for encrypting user metadata used by Sync.

- CHANGELOG.md
- packages/cinterop/src/jvmMain/kotlin/io/realm/kotlin/jvm/SoLoader.kt
Closes https://github.com/realm/realm-kotlin/issues/1105
This PR adds support for bundling Realm inside apps distributed using 3rd party JVM installers like [Hydraulic Conveyor](https://conveyor.hydraulic.dev/4.0/).
It does this by changing how we load the native library. After this change we first attempt to load the library using `System.loadLibrary(name)` which will search all paths defined by `java.libraries.path`. If this fails we will fall back to finding the native library inside the JAR file as before this change.
We make no attempt at detecting if the correct native code is linked as users might have modified the binary, so any checks we employ could fail. But that also means that it is up to developers to make sure that the correct native file is loaded. I will create a ticket …
> Add support for loading native library code from a custom location on JVM

- CHANGELOG.md
Adds query validation back + capabilities for shutting down sync client thread on JVM
> Update to upcoming Core 12.13.0

- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/BsonObjectIdTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/ByteArrayTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/CopyFromRealmTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/ObjectIdTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/QueryTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/RealmInMemoryTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/RealmInstantTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/RealmSchemaTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/nonlatin/NonLatinTests.kt
- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SubscriptionSetTests.kt
For realms declared using `lateinit var realm: Realm`, this PR replaces:
```kt
@AfterTest
fun tearDown() {
if (!realm.isClosed()) {
realm.close()
}
PlatformUtils.deleteTempDir(tmpDir)
}
```
with:
```kt
@AfterTest
fun tearDown() {
if (this::realm.isInitialized && !realm.isClosed()) {
realm.close()
}
PlatformUtils.deleteTempDir(tmpDir)
}
```
> Ensure realm has been initialized before checking isClosed.

- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/Configuration.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmUtils.kt
- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SyncConfigTests.kt
Closes #1060.
If KMM users forget to add the Kotlin plugin, the error message is now more appropriate.
> Improve error message when forgetting plugin.

- CHANGELOG.md
- CONTRIBUTING.md
- packages/jni-swig-stub/realm.i
Typemap for jlong has been fixed in Swig 4.1.0 (https://github.com/swig/swig/pull/1934) so remove custom typemap. 
Closes #1144
> Remove swig jlong typemap workaround

- CHANGELOG.md
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelLoweringExtension.kt
- packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/ModelDefinitionTests.kt
Similar to https://github.com/realm/realm-kotlin/pull/698 but for enum classes, object declarations, and anonymous objects.
Closes https://github.com/realm/realm-kotlin/issues/1086
> Add error message for unsupported class types and objects

- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/ObjectIdImpl.kt
Align the implementation of Realm ObjectId and KBSON Object by delegating all implementation details to KBSON while maintaining the public API.
This isn't a fix for the potential problem seen in https://github.com/realm/realm-kotlin/issues/1154, but make sure that if we have any bugs, the behavior is the same.
> Realm ObjectId delegate all responsibility to KBSON ObjectId

- packages/cinterop/build.gradle.kts
- packages/jni-swig-stub/realm.i
This prevents generating parser files which made it harder to switch Git Submodule versions. This fix was verified locally to work.
> Pretend to build Core as a submodule for MacOS

- CHANGELOG.md
- packages/library-base/src/nativeDarwin/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/RealmInstantTests.kt
Closes #1182 
We were hoping that converting the `RealmInstant.MAX` and `MIN` values to milliseconds would allow us to compare them to the current milliseconds value returned by `NSDate().timeIntervalSince1970`. However, the `MAX` and `MIN` values use `Long.MAX` and `Long.MIN` respectively and by multiplying them by `1000` we were overflowing causing the value to be `0` and always return `RealmInstant.MAX`.
This has been solved by comparing the value returned by `NSDate().timeIntervalSince1970` to the `MAX` and `MIN` values in seconds.
> Fix `Long` overflow when comparing current time to `RealmInstant.MAX` and `MIN` values

- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/types/annotations/Index.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelSyntheticPropertiesGeneration.kt
- packages/test-base/src/commonMain/kotlin/io/realm/kotlin/test/util/TypeDescriptor.kt
This PR would remove our compiler plugin check that erroneously guarded against marking boolean properties as indexed.
Closes #1193
> Allow indexes on boolean properties

- CHANGELOG.md
- packages/cinterop/src/androidAndroidTest/kotlin/io/realm/kotlin/test/CinteropTest.kt
- packages/library-base/src/nativeDarwin/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/RealmConfigurationTests.kt
- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SyncSessionTests.kt
> Allow white spaces in realm file path on iOS

- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/ext/RealmDictionaryExt.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmObjectHelper.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/types/RealmMap.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/types/RealmSet.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/AccessorModifierIrGeneration.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/Identifiers.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelSyntheticPropertiesGeneration.kt
- packages/test-base/src/commonMain/kotlin/io/realm/kotlin/test/util/TypeDescriptor.kt
- packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/EmbeddedTests.kt
- packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/Utils.kt
- packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/dictionary/DictionaryTests.kt
- packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/list/ListTests.kt
- packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/set/SetTests.kt
- Added draft interface for `RealmDictionary` and support for it in the compiler plugin.
- Added compiler plugin tests for dictionaries - I will align tests for lists, sets and dictionaries in an upcoming PR since there is a lot of similarities among them
> `RealmDictionary` - compiler plugin support

- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/ext/IterableExt.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/ext/RealmDictionaryExt.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/CollectionOperator.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmListInternal.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmMapInternal.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmObjectHelper.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmSetInternal.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/types/RealmMap.kt
- Added the basic infrastructure and API operations with stubs for later implementation. In principle the interfaces should (hopefully) not change in the upcoming pull requests.
- Added helper functions for creating dictionaries as stubs for now.
- Slightly modified some aspects in connection with collection operators for better alignment with lists and sets.
Pull request plan:
> `RealmDictionary` - 1: basic infrastructure and API stubs

- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SyncedRealmTests.kt
Closes #1235 
This solution is rather slow, but locks are not generally available on Native. 
AtomicFu does have a `SynchronizationObject` that could be locked, but all primitives for that was in a package marked "very much experimental", so I opted for something more stable.
> Synchronize access to list of logs

- packages/cinterop/build.gradle.kts
This ensure that we clean `cinterop` files that are not placed in `cinterop/build`.
> Add missing outputs to cinterop clean task

- CHANGELOG.md
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/ext/BaseRealmObjectExt.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/ext/RealmListExt.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/ext/RealmSetExt.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmObjectHelper.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmSetInternal.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/types/RealmSet.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/RealmSetTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/dynamic/DynamicRealmObjectTests.kt
- packages/test-base/src/commonMain/kotlin/io/realm/kotlin/entities/set/RealmSetContainer.kt
Closes #1258
We needed to add support for queries on `RealmSet`s. The API follows the same pattern for `RealmList` due to the `BaseRealmObject` upper bound in `RealmQuery` and exposes `query` as an extension function.
Also refined some wording in a few documentation places and added missing imports for their respective links.
> Add support for querying on `RealmSet`

- buildSrc/src/main/kotlin/Config.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/Registrar.kt
- packages/plugin-compiler/src/main/resources/META-INF/services/org.jetbrains.kotlin.compiler.plugin.ComponentRegistrar
- packages/plugin-compiler/src/test/kotlin/io/realm/kotlin/compiler/GenerationExtensionTest.kt
This PR will change the order of registration of our compiler plugin, so that it is applied after other plugins. This will avoid having other plugins processing our internal `io.realm.kotlin.x`-attributes.
*Reviewing considerations*
I found it hard to put up a test that verifies this across Kotlin versions in the current integration test infrastructure. If we add it in `test-base` it is only verified for Kotlin version of the SDK and if enabling serialization in `examples/kmm-sample` it would only be verified for `Versions.latestKotlin`. I guess the right approach would be to add feature specific projects in `integration-tests/compatibility/<feature>` and trigger those for both `Versions.kotlin` and `Versions.latestKotlin` ... But didn't deem it for this PR!?
Test for current level of …
> Apply Realm Kotlin compiler plugin after other plugins

- CHANGELOG.md
- examples/realm-java-compatibility/app/src/main/java/io/realm/kotlin/demo/javacompatibility/data/java/JavaRepository.kt
- examples/realm-java-compatibility/app/src/main/java/io/realm/kotlin/demo/javacompatibility/data/kotlin/KotlinRepository.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/IrUtils.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelLoweringExtension.kt
Closes #1278 
The logic for checking the PSI tree was a bit complex so not sure if there is an easier way to do this, but it seems to fix the problem. I added the problematic case to our Java integration sample so we can catch future regressions.
> Fix issue when compiling project containing a Realm Java model class using the RealmObject abstract class

- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmUUIDImpl.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/RealmUUIDTests.kt
Fixes https://github.com/realm/realm-kotlin/issues/1288
Comparing a `RealmUUID` instance with an object instance of a different type resulted on a `ClassCastException`
> Fix RealmUUID equal comparison

- CHANGELOG.md
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/Callback.kt
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/jvm/jni/env_utils.cpp
- packages/cinterop/src/jvm/jni/env_utils.h
- packages/cinterop/src/jvm/jni/java_class_global_def.hpp
- packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/jni-swig-stub/realm.i
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.h
- packages/library-base/proguard-rules-consumer-common.pro
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/AppConfigurationImpl.kt
- packages/test-sync/src/jvmTest/kotlin/io/realm/kotlin/jvm/RealmTests.kt
Close https://github.com/realm/realm-kotlin/issues/1290
This PR makes sure we correctly clean up the Sync thread. This is currently leaking, which on the JVM prevents it from shutting down gracefully, and depending on your usage (like in #1290), it might also be a big resource drain.
There is an open question about how to handle exceptions on the Sync thread. Ideally, they should never happen and they are reported back to us as just a string. For now, I just print them (waiting for proper logging), but we could also consider throwing an exception, but it will 100% tear the app down with it. 
In Java, we throw an Exception, and I don't think we have seen
> Correctly cleanup Sync Client thread when it is destroyed on the C++ side

- CHANGELOG.md
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SyncSessionImpl.kt
This was accidentally discovered during testing another project. We have had flaky tests in the past because of this, but I think we contributed those test failures to the async nature of the server and the translator.
I could 100% reproduce this by doing:
```
// Write to Realm 1
repeat(1000) {
realm1.write { copyToRealm(MyObject()) }
}
realm1.syncSession.uploadAllLocalChanges()
realm1.close()
// Download objects for Realm2
// It would not see all 1000 objects
```
It would result in the client cutting off some transactions meaning other devices saw anywhere from 500 - 950-ish objects.
I haven't added a test for this in this PR since the above test takes a couple of minutes to run, and it doesn't seem worth it to add that expensive of a test.
> Fix SyncSession.uploadAllLocalChanges and SyncSession.downloadAllServerChanges

- packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/ConfigurationImpl.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
- packages/library-base/src/jvm/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
- packages/library-base/src/nativeDarwin/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/AppConfiguration.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/ApiKeyAuthImpl.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/AppConfigurationImpl.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/AppImpl.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/EmailPasswordAuthImpl.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/HttpClientCache.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SubscriptionSetImpl.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SyncConfigurationImpl.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SyncSessionImpl.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/UserImpl.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/notifications/RealmDictionaryNotificationsTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/notifications/RealmListNotificationsTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/notifications/RealmSetNotificationsTests.kt
- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SyncSessionTests.kt
- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SyncedRealmTests.kt
Closes #1294 
This PR removes all uses of `freeze`. It was already a no-op when moving to the new memory model and we just kept it to be able to shift back easily. But there has been no pushback against moving to the new memory model, so might as well cleanup the code.
> Remove all uses of freeze

- CHANGELOG.md
- examples/realm-java-compatibility/app/src/androidTest/java/io/realm/kotlin/demo/javacompatibility/InstrumentedTest.kt
- examples/realm-java-compatibility/app/src/main/java/io/realm/kotlin/demo/javacompatibility/data/java/JavaRepository.kt
- examples/realm-java-compatibility/app/src/main/java/io/realm/kotlin/demo/javacompatibility/data/kotlin/KotlinRepository.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/AccessorModifierIrGeneration.kt
- packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/ModelDefinitionTests.kt
Closes https://github.com/realm/realm-kotlin/issues/1226
This mirrors the behavior in Realm Java, where we also fail at compile time for unknown types.
> Fail build if model class contain types not supported.

- CHANGELOG.md
- benchmarks/androidApp/build.gradle.kts
- buildSrc/src/main/kotlin/Config.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/LogObfuscator.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/QueryTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/RealmAnyTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/RealmInMemoryTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/RealmTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/notifications/BacklinksNotificationsTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/notifications/RealmDictionaryNotificationsTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/notifications/RealmListNotificationsTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/notifications/RealmNotificationsTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/notifications/RealmObjectNotificationsTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/notifications/RealmResultsNotificationsTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/notifications/RealmSetNotificationsTests.kt
- packages/test-base/src/commonMain/kotlin/io/realm/kotlin/test/util/Utils.kt
- packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/jvm/RealmTests.kt
- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/HttpLogObfuscatorTests.kt
- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SyncClientResetIntegrationTests.kt
- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SyncSessionTests.kt
- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SyncedRealmTests.kt
- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/internal/KtorNetworkTransportTest.kt
- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/nonlatin/NonLatinTests.kt
This PR adds a new extension method `Channel.receiveOrFail` that mirrors the `TestHelper.awaitOrFail` in Realm Java. This prevents tests using channels from hanging forever.
I considered wrapping our `runBlocking` method, but this approach will better pinpoint the point of failure and is also easy to use.
I also sneaked in an update of Ktor + an update of the obfuscation tests since that was what prompted this improvement in the first place (those changes are constrained to the [LogObfuscator](https://github.com/realm/realm-kotlin/compare/cm/receiveOrFail?expand=1#diff-25cf77886f487923d744109883ee33b72a5265f1e9f2517cf5015882a61b8711R160) and [HttpLogObfuscatorTests](https://github.com/realm/realm-kotlin/compare/cm/receiveOrFail?expand=1#diff-3080fa7a4048c742433e12073f913ff16136b82326b833dd …
> Add receiveOrFail for better testing

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature.yml
This adds a menu and forms for creating new issues. Just grabbed the Java templates and updated the link to the forum to show the kotlin issues instead.
> Add GitHub issue templates

- buildSrc/src/main/kotlin/Config.kt
- packages/gradle.properties
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/AppConfiguration.kt
- packages/test-sync/build.gradle.kts
- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/EmailPasswordAuthTests.kt
- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/FunctionsTests.kt
- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/HttpLogObfuscatorTests.kt
- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/ProgressListenerTests.kt
- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/internal/KtorNetworkTransportTest.kt
- packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/TestApp.kt
- packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/util/AppServicesClient.kt
- packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/util/HttpClient.kt
- packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/util/TestAppInitializer.kt
- tools/delete-cloud-qa-apps.sh
This PR adds support for running all Sync integration tests on either a local BAAS server or on Cloud QA. If running on Cloud, a Cluster must have been set up before starting the tests and the name of that cluster must be provided.
Cleaning up apps are optional as they will be wiped periodically on Cloud anyway, but it is recommended if running tests multiple times in a row.
API Keys can be found in 1Password.
> Add support for running tests on Cloud QA

- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/ConfigurationImpl.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/types/annotations/PersistedName.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/IrUtils.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelSyntheticPropertiesGeneration.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/PersistedNameTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/RealmSchemaTests.kt
Closes https://github.com/realm/realm-kotlin/issues/1138
This PR introduces a new level of complexity to opening Realms as we can only detect schema mismatch as part of creating or opening the Realm.
Our current code set up the native RealmSchema when creating the RealmConfiguration, but the schema isn't validated until the Realm is opened. I opted for placing the checking code for this in the same location, but it also means that we can now throw IllegalArgumentException when creating the RealmConfiguration. 
Not 100% sure what the best approach is, so any feedback here would be nice.
> Add support for @PersistedName on classes

- CHANGELOG.md
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/jni-swig-stub/realm.i
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/Realm.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
- packages/library-base/src/jvm/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
- packages/library-base/src/nativeDarwin/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/RealmTests.kt
Closes #571 
This adds support for a manual compact method which has come up a few times as something people want to do (instead of having to open the Realm for either `compactOnLaunch` or `writeCopyTo`). This method also exists in Realm Java.
Core currently has a warning about this method not being safe on Windows, so we are currently throwing an exception on JVM there. See https://github.com/realm/realm-core/issues/4111 for more context.
> Add support for Realm.compactRealm()

- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmImpl.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/VersionTrackingTests.kt
- packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SyncedRealmTests.kt
This PR ensures that we will register a changelistener in the notifier, so that it is up-to-date when the user facing `Realm` is considering whether to advance its own version on an as-needed-basis.
> Reflect background updates in realm without listeners

- CHANGELOG.md
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/Callback.kt
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/CoreErrorConverter.kt
- packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/ConfigurationImpl.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/CompactOnLaunchTests.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/migration/RealmMigrationTests.kt
This PR adds support for propagating user exceptions on the following callbacks:
- Migration
- Should compact on launch
- Realm data initialization
Client reset handlers do not support user exception propagation as it is not implemented in `SyncError` yet. https://github.com/realm/realm-core/issues/6569
Closes #1228
> Propagate callback user exceptions

- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/Realm.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/CompactOnLaunchTests.kt
Replacement for https://github.com/realm/realm-kotlin/pull/1382 to get CI validation.
Closes https://github.com/realm/realm-kotlin/issues/1380
> Fix compact on launch to run when less than 50% is used

- CHANGELOG.md
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelSyntheticPropertiesGeneration.kt
- packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/PersistedNameTests.kt
Fixes the issue where objects that had defined a persisted name were not able to be linked.
The Realm failed to load by throwing an exception when loading the schema.
#closes https://github.com/realm/realm-kotlin/issues/1377
> Fix persisted name object links

- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/types/annotations/Ignore.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/AccessorModifierIrGeneration.kt
- packages/plugin-compiler/src/test/resources/sample/expected/01_AFTER.ValidateIrBeforeLowering.ir
- packages/plugin-compiler/src/test/resources/sample/input/Sample.kt
Delegated properties did not support the `@Ignore` annotation. This was preventing the users to write their own custom delegated properties.
This would help users to write delegates on Realm types to do any conversion to their own custom types.
#closes https://github.com/realm/realm-kotlin/issues/1381
> Add support for ignoring delegated properties

- CHANGELOG.md
- Jenkinsfile
- examples/kmm-sample/androidApp/build.gradle.kts
- packages/gradle-plugin/src/main/kotlin/io/realm/kotlin/gradle/RealmPlugin.kt
Automatically apply the dependency substitution used for our own tests in https://github.com/realm/realm-kotlin/pull/1399 to user projects.
We need to do the dependency substitution manually in our tests as we are not applying the plugin there but just calling the compiler plugin.
With the plugin doing this, running Android tests on the JVM should "just work" for users.
I added a step to our CI pipeline that verifies that this behavior works on Android projects. Kotlin Multiplatform just delegate to Android for this, so I don't think we need to also test Multiplatform projects.
> Add support for running Android Unit Tests on the JVM

- CHANGELOG.md
- benchmarks/androidApp/build.gradle.kts
- benchmarks/androidApp/src/androidTest/AndroidManifest.xml
- buildSrc/src/main/kotlin/Config.kt
- packages/test-base/src/androidMain/AndroidManifest.xml
- packages/test-sync/src/androidMain/AndroidManifest.xml
With these changes, it is now possible to profile unit tests running.
Note, that the "low overhead"-mode requires a non-debuggable emulator that is minimum API 29.
I tested with the latest API 34 arme-v8a emulator which worked fine.
If you run profilers from the "run-command", note, it doesn't automatically open and attach the session, which can make timing tricky on short-lived tests:
Instead, this must be done manually:
This can be done by running the test in debug mode, set a breakpoint, attach the session, and then continue the test. But be aware that the profiler is now running on a debug build.
But then the output should work:
> Enable profiling for memory tests

- CHANGELOG.md
- packages/cinterop/src/androidInstrumentedTest/kotlin/io/realm/kotlin/test/CinteropTest.kt
- packages/cinterop/src/androidMain/kotlin/io/realm/kotlin/internal/AndroidUtils.kt
- packages/cinterop/src/nativeDarwinTest/kotlin/io/realm/kotlin/test/CinteropTest.kt
An attempt at fixing #https://github.com/realm/realm-kotlin/issues/1202,  but since we have never been able to reproduce it it's just a guess. But regardless, Relinker should not be needed at those API levels anyway.
Also bumps to the latest core version and removes the version checks which are just getting in our way for every core release, without providing any real value.
> Disable Relinker on API 23 and above

- CHANGELOG.md
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SyncConfigurationImpl.kt
Closes #1438 
I also discovered that we didn't check whether a realm file existed or not before triggering `waitForInitialRemoteData`, this meant that if `waitForInitialRemoteData` was enabled, the device would always require a network connection before opening the realm file, even after being opened for the first time.
It isn't really possible to write a test for this since it would require us to be able to cut the internet connection between opening the Realm for the first and second time. But I verified the behavior manually.
> Use async open for FLX Realms

- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/types/RealmInstant.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmInstantTests.kt
RealmInstant requires that both constructor's parameters be positive or negative, but never a mix of them.
> Fix RealmInstant accepting invalid constructor parameters

- CHANGELOG.md
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/AppConfiguration.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/HttpClientCache.kt
Http requests where only logged when loglevel was set in `AppConfiguration`, this PR enables HTTP request logs when set via `LogLevel.log`
> Log HTTP request when level is set in `LogLevel.log`

- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/Configuration.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/AppConfiguration.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/AppConfigurationImpl.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/sync/SyncConfiguration.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmConfigurationTests.kt
- packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/TestApp.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AppConfigurationTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncConfigTests.kt
Sync events are not logged when `RealmLog.level` is set. Any level previously defined is ignored, except if it is defined via the deprecated `AppConfiguration.Builder.log`.
The reason the level is ignored is because whenever an App or Realm configuration is set the log level is set to a default level of `WARN`.
This PR fixes the issue by setting the default level to the `RealmLog.level`, this way, if the user does not define any level via the deprecated method, we will set the level to whatever was already defined.
> Fix `RealmLog` does not log sync events

- tools/fix-h1s.sh
- tools/publish_release.sh
This is an SEO team request to make sure all pages have an H1.
For more info see https://jira.mongodb.org/browse/DOCSP-31274
This has not been fully tested due to my lack of environment that can successfully build the Dokka files. Please validate.
> Add script to fix H1s on Dokka-generated docs

- CHANGELOG.md
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/RealmConfiguration.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/ConfigurationImpl.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmConfigurationImpl.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/sync/SyncConfiguration.kt
- packages/test-base/src/commonMain/kotlin/io/realm/kotlin/entities/migration/embedded/after/EmbeddedMigrationChild.kt
- packages/test-base/src/commonMain/kotlin/io/realm/kotlin/entities/migration/embedded/after/EmbeddedMigrationParent.kt
- packages/test-base/src/commonMain/kotlin/io/realm/kotlin/entities/migration/embedded/before/EmbeddedMigrationChild.kt
- packages/test-base/src/commonMain/kotlin/io/realm/kotlin/entities/migration/embedded/before/EmbeddedMigrationParent.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/MigrationTests.kt
This adds configuration option to enable automatic handling of embedded object constraints during automatic migration through:
```
class RealmConfiguration {
class Builder {
/**
* Sets the migration to handle schema updates with automatic migration of data.
*
* @param migration the [AutomaticSchemaMigration] instance to handle schema and data
* migration in the event of a schema update.
* @param resolveEmbeddedObjectConstraints a flag to indicate whether realm should resolve
* embedded object constraints after migration. If this is `true` then all embedded objects
* without a parent will be deleted and every embedded object with multiple references to it
* will be duplicated so that every referencing object will hold its own copy of the
* embedded object.
*
* @see RealmMigration
* @see …
```
> Add automatic resolution of embedded object constraints during migration

- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/AccessorModifierIrGeneration.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/Identifiers.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/IrUtils.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelLoweringExtension.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelSyntheticPropertiesGeneration.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/SyncLoweringExtension.kt
- packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/CollectionTests.kt
This PR reworks the compiler plugin, so it no longer uses deprecated APIs. This should move us closer to K2 support, but I'm keeping support out of this for now.
- All APIs using descriptors have been changed to IR-based APIs.
- All APIs marked with `@FirIncompatiblePluginAPI` has been reworked.
- Both of the two above required changing from using `FqNames` to `ClassId` and `CallableId`.
Regarding testing. Our library is built and tested with Kotlin 1.8.21. We do have a minimal sample project being built with 1.8.20, but I'll see if all tests run on 1.8.20 as well, just to be sure we are not breaking backwards compatibility.
> Remove all deprecated APIs from the compiler plugin.

- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmObjectHelper.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmObjectUtil.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmUtils.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
- packages/library-base/src/jvm/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
- packages/library-base/src/nativeDarwin/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelDefaultMethodGeneration.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelLoweringExtension.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelSyntheticCompanionExtension.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelSyntheticMethodsExtension.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/Registrar.kt
- packages/plugin-compiler/src/test/resources/sample/expected/01_AFTER.ValidateIrBeforeLowering.ir
- packages/plugin-compiler/src/test/resources/schema/expected/01_AFTER.ValidateIrBeforeLowering.ir
- packages/test-base/src/commonMain/kotlin/io/realm/kotlin/entities/link/Parent.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmListTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmObjectTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmSetTests.kt
Closes https://github.com/realm/realm-kotlin/issues/1097
This PR adds custom `toString`, `equals`, and `hashCode` implementations to Realm Object subclasses. If these methods already exist, nothing will be generated. 
TODO
> Add custom implementations for toString, equals and hashCode

- CHANGELOG.md
- packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.h
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/types/annotations/FullText.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/VersionTrackingTests.kt
Closes #1502 
This PR aligns the behavior of schedulers across all platforms. Previously Darwin was using their custom run-loop, which was why it worked there while Linux and Windows failed.
The fix has been verified on Github Actions: https://github.com/realm/realm-kotlin/actions/runs/6098168339
> Fix missing scheduler on Linux and Windows (JVM)

- packages/test-base/src/androidInstrumentedTest/kotlin/io/realm/kotlin/test/android/MemoryTests.kt
The old version of test was erroneously storing references to live objects, thus wouldn't ever hold on to any frozen versions beside the initial object. The test was actually ok, but it is now easier to play around with not clearing the references as it is just a matter of commenting out `referenceHolder.clear()` to make the test fail.
> Fix test around releasing intermediate versions

- CHANGELOG.md
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/HttpClientCache.kt
- packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/util/HttpClient.kt
Discovered this while testing a Windows build against a production server.
Our local dev server does not cause redirects, so I don't think there is a way to add a test for this. The fix was verified manually on both JVM and Darwin.
> Fix redirects only working for GET requests.

- CHANGELOG.md
- benchmarks/androidApp/build.gradle.kts
- benchmarks/build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/Config.kt
- buildSrc/src/main/kotlin/realm-lint.gradle.kts
- examples/kmm-sample/androidApp/build.gradle.kts
- examples/kmm-sample/compose-desktop/build.gradle.kts
- examples/realm-java-compatibility/app/build.gradle
- integration-tests/gradle-plugin-test/single-platform/build.gradle.kts
- packages/build.gradle.kts
- packages/cinterop/build.gradle.kts
- packages/gradle-plugin/build.gradle.kts
- packages/gradle-plugin/src/main/kotlin/io/realm/kotlin/gradle/RealmPlugin.kt
- packages/jni-swig-stub/build.gradle.kts
- packages/library-base/build.gradle.kts
- packages/library-sync/build.gradle.kts
- packages/plugin-compiler-shaded/build.gradle.kts
- packages/plugin-compiler/build.gradle.kts
- packages/test-base/build.gradle.kts
- packages/test-sync/build.gradle.kts
From Kotlin 1.8.0 the minimum supported Java target is 1.8. This means there is no longer any reason we are setting this in our Realm Plugin. In fact, it might silently modify the behavior of people's compiled code if they are not setting the jvmTarget themselves: https://kotlinlang.org/docs/whatsnew18.html#updated-jvm-compilation-target
I tested this with various combinations of  Java (11 and 17)  and `build.gradle` settings and it doesn't seem to cause build failures.
At the same time, I also unified how we are setting the Kotlin and Java bytecode versions, so they can now all be controlled through our buildSrc Config file.
Regarding the target version, I kept it at 1.8 since we don't know what version of the JVM people are running on the desktop.  On Android the minimum the 11, but it …
> Remove Realm Plugin setting the bytecode target to 1.8

- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmConfigurationTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AppConfigurationTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/FlexibleSyncConfigurationTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncConfigTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncedRealmTests.kt
Some tests in `SyncConfigTests` assumed some things about path separators that it shouldn't
> Fix SyncConfig tests that would break on Windows

- CHANGELOG.md
`getNumberOfActiveVersions` did not return the actual number of active versions but the difference between the earliest and latest opened versions.
With this PR we include the core fix for this issue, `getNumberOfActiveVersions` would return the actual number of active versions.
> Fix `numberOfActiveVersions`

- CHANGELOG.md
- dependencies.list
- packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmImpl.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/exceptions/ClientResetRequiredException.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SyncConfigurationImpl.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SyncSessionImpl.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SyncedRealmContext.kt
- packages/test-base/src/androidMain/kotlin/io/realm/kotlin/test/platform/PlatformUtils.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmTests.kt
- packages/test-sync/build.gradle.kts
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AppConfigurationTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AsymmetricSyncTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/FlexibleSyncIntegrationTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/MutableSubscriptionSetTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/ProgressListenerTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/Schema.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SubscriptionExtensionsTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SubscriptionSetTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SubscriptionTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncClientResetIntegrationTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncClientTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncConfigTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncSessionTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncedRealmTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/nonlatin/NonLatinTests.kt
This PR fixes some problems I discovered on Windows.
- During Client Reset we were not closing a realm instance correctly, which will prevent the Realm file from being deleted later. This fixed most of our Client Reset Tests on Windows, which all timed out during tearDown.
- Manually closing the SyncSession Pointer when closing the Realm make shutdown more predictable. Before this, it was GC dependant.
- I switched to a more accurate pattern for testing client resets rather than us "faking" it.
- I haven't added a changelog entry since we are still leaking something during a manual client reset. I'm still trying to hunt that one down.
> Cleanup resources better during Client Reset and closing Realms.

- CHANGELOG.md
- packages/gradle-plugin/build.gradle.kts
Closes #1513 
Fixes the error in #1513, but it will just move the error to another. Most likely 
```
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlinAndroid' task (current target is 17) jvm target compatibility should be set to the same Java version.
Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
```
> Remove dependency on KAPT

- CHANGELOG.md
- packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/SynchronizableObjectDarwin.kt
A reference cycle between `CPointerWrapper` and its cleaner was causing a leak were the GC was not reclaiming any native memory. 
This PR breaks the cycle by moving the `CPointerWrapper` and cleaner shared data into a new data class.
See [LeakingCleaner](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.native.ref/create-cleaner.html).
> Fix darwin native leak

- packages/cinterop/src/nativeDarwinTest/kotlin/io/realm/kotlin/test/CinteropTest.kt
- packages/test-base/src/nativeDarwinTest/kotlin/io/realm/kotlin/test/darwin/MemoryTests.kt
Adds a test case to catch whether we are releasing realm pointers.
> Tests GC realm pointer release

- CHANGELOG.md
- dependencies.list
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/User.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/UserImpl.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/sync/SyncConfiguration.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AppTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/FlexibleSyncIntegrationTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncClientResetIntegrationTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncConfigTests.kt
Bumps core to version 13.23.0.
Core has removed `realm_user_get_auth_provider`, in reaction to this we have annotated `User.provider` as deprecated and now returns the first element auth provider at `User.identities`.
> Bump core to version 13.23.1

- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/query/ObjectQuery.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/schema/CachedClassKeyMap.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/PersistedNameTests.kt
Closes https://github.com/realm/realm-kotlin/issues/1555
Aggregators on properties annotated with @PersistedName triggered an NPE. The cause was that we used the public names to retrieve the schema metadata when they were only accessible via the persisted one.
This PR fixes the issue by retrieving the object schema via the classkey, and then allowing retrieving properties via both persisted and public names.
> Allow aggregators on properties annotated with @PersistedName

- packages/test-base/src/commonMain/kotlin/io/realm/kotlin/entities/Sample.kt
- packages/test-base/src/commonMain/kotlin/io/realm/kotlin/entities/migration/Sample.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/PersistedNameTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/migration/RealmMigrationTests.kt
> DynamicObjects can now access fields by public name.

- CHANGELOG.md
- buildSrc/src/main/kotlin/Config.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/SyncLoweringExtension.kt
Fixes #1566  toIrConst moved under common IrUtils in Kotlin 1.9.20 https://github.com/JetBrains/kotlin/commit/ca8db7d0b83f6dfd6afcea7a5fe7556d38f325d8 
`bundleId` is a string so we can work around using `toIrConstOrNull` by using `IrConstImpl.string`
> Fixing compiler crash when using 1.9.20 with Sync

- benchmarks/settings.gradle.kts
- buildSrc/src/main/kotlin/Config.kt
- examples/kmm-sample/settings.gradle.kts
- examples/realm-java-compatibility/settings.gradle.kts
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/Configuration.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/ConfigurationImpl.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/Decimal128Tests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/EmbeddedRealmObjectTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/FqNameImportTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/ImportTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/LinkTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/NullabilityTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/ReadMeTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmConfigurationTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmInMemoryTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/migration/RealmMigrationTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmNotificationsTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/SystemNotificationTests.kt
- packages/test-base/src/jvmMain/kotlin/io/realm/kotlin/test/platform/PlatformUtils.kt
- packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/jvm/RealmTests.kt
This PR is an attempt to cleanup https://github.com/realm/realm-kotlin/pull/881
- It pulls out a number of smaller fixes to out test suit which resulted in errors when running tests on Windows.
- Improves the CI check to check for both Jenkins and GHA
- Increases the wait period for some tests that timed out when running on GHA
> Fix corner cases in tests discovered after running on Github Actions

- CHANGELOG.md
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
There were some instances where a sync app would crash after enabling log-level `Trace` or `All`.
The cause is that objects instantiated in JNI were not reclaimed and could cause an Out Of Memory exception or a local reference table overflow.
This PR attempts to release any local instances by using the local frames.
Testing was done locally.
> Delete local references

- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SubscriptionSetImpl.kt
- packages/test-base/src/commonMain/kotlin/io/realm/kotlin/test/util/Utils.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/QueryTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmAnyTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmInMemoryTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/VersionTrackingTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/BacklinksNotificationsTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmDictionaryNotificationsTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmListNotificationsTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmNotificationsTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmObjectNotificationsTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmResultsNotificationsTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmSetNotificationsTests.kt
- packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/jvm/RealmTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AppConfigurationTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AppTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/FlexibleSyncIntegrationTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/HttpLogObfuscatorTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncClientResetIntegrationTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncSessionTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncedRealmTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/internal/KtorNetworkTransportTest.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/nonlatin/NonLatinTests.kt
This PR streamlines how we are using Channels in tests by introducing a new TestChannel factory method which will ensure we construct the same channel across all tests.
This channel has a few changes compared to the previous one:
- It has an unlimited buffer, which means that `send` should never suspend and we should never accidentally overwrite an event.
- When the channel is canceled, it will check if some elements have not been delivered and throw an assertion if that is true (as it indicates the writer of the test doesn't fully understand the event flow)
I also refactored `Channel.receiveOrFail()`, `onReceive` in channels does not consume elements and we suspect it might be the cause of some of our flaky tests (but hasn't been 100% confirmed).
All uses of `trySend()` in tests has also …
> Improve tests using Channels

- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmImpl.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/SuspendableNotifier.kt
Fixes errors like  `❌ asFlow_objectBound_withKeyPath[jvm] java.lang.IllegalStateException: [RLM_ERR_WRONG_THREAD]: Realm accessed from incorrect thread.`, but could happen with any KeyPath.
The problem was that we were calling a function in the notifier (from an arbitrary thread), and then using the notifier Realm (outside the notifier thread). So depending on the timing, sometimes it would return a thread-confined Realm.
I refactored the code, so we now calculate the keypath array outside the notifier using the caller Realm which should always be safe.
> Use caller Realm instead of Notifier Realm when calculating KeyPaths.

- CHANGELOG.md
- packages/cinterop/src/jvm/jni/java_class_global_def.hpp
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
> Cache notification callback JNI class references at startup

- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmImpl.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/SuspendableNotifier.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmDictionaryTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmListTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmSetTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/VersionTrackingTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmNotificationsTests.kt
Closes #1582
Closes https://github.com/realm/realm-kotlin/issues/1574
> Fix Realm.asFlow() potentially missing an update when doing a write immediately after opening the Realm

- Jenkinsfile
- packages/build.gradle.kts
- packages/cinterop/build.gradle.kts
- packages/gradle.properties
- packages/library-base/build.gradle.kts
- packages/library-sync/build.gradle.kts
With this change, it is now possible to define which targets to build using. It does this by introducing a new target `publishCIPackages`, which can be configured using a number of new Gradle properties:
```
realm.kotlin.mainHost=true
realm.kotlin.targets=<CommaSeperatedListOfPublications>
realm.kotlin.buildRealmCore=true
realm.kotlin.copyNativeJvmLibs=false
```
With this it is possible to get fine-grained control over exactly what gets built on a CI runner. 
This PR is mostly moving things out of #881, so we can keep the review more focused.
> Add new publishCIPackages target in Gradle to make it easier to control which targets to build on a given platform

- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/SuspendableWriter.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmTests.kt
> Cancel transactions on all kind of exceptions

- packages/cinterop/build.gradle.kts
I made a mistake in https://github.com/realm/realm-kotlin/pull/1607 so we didn't copy native libs for Linux and Windows correctly. It only worked on CI because the MacOS JVM libs where in the correct place because of them being built in-place on Jenkins and we do not run Windows/Linux tests there.
But it was caught by our Github Actions branch.
I added an extra debug log that makes it easier to check for in the future.
> Fix native libs other than macos being copied correctly.

- Jenkinsfile
- packages/cinterop/build.gradle.kts
- packages/gradle.properties
When I merged https://github.com/realm/realm-kotlin/pull/1607 I forgot to account for Jenkins only copying 2 architectures  rather than all 3 as on Github Actions. 
This is now made configurable. The default is still that no copying is done.
> Make it configurable which native libs to copy when building

- .github/actions/run-android-device-farm-test/action.yml
- .github/workflows/pr.yml
- packages/test-sync/src/androidMain/kotlin/io/realm/kotlin/test/mongodb/BaasUtils.kt
- packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/TestApp.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/CredentialsTests.kt
- packages/test-sync/src/jvmMain/kotlin/io/realm/kotlin/test/mongodb/BaasUtils.kt
- packages/test-sync/src/nativeDarwin/kotlin/io/realm/kotlin/test/mongodb/BaasUtils.kt
Using AndroidTestRunner to parametrise the URL of the BAAS server when running Sync tests on Device Farm. We now can replay the sync test without the need to rebuild the APK. see https://github.com/realm/realm-kotlin/actions/runs/7679635078/job/20931215946#step:8:43
> Using test parameter to feed BAAS URL to device farm

- CHANGELOG.md
- tools/publish_snapshots.main.kts
Fixes https://github.com/realm/realm-kotlin/issues/1654
> [GHA] build number for Snapshot not being consistent over published artifacts

- .github/workflows/pr.yml
- CHANGELOG.md
- CONTRIBUTING.md
- packages/jni-swig-stub/realm.i
Closes #1632/[RKOTLIN-1001](https://jira.mongodb.org/browse/RKOTLIN-1001)
> Update to Swig 4.2.0

- CHANGELOG.md
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmListInternal.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmAnyNestedCollectionTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmListTests.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmAnyNestedListNotificationTest.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmListNotificationsTests.kt
This PR passes arguments to `RealmList`s `indexOf`, `remove` and `contains` to core instead of relying on Kotlin object equality checks. 
Closes #1625 RKOTLIN-995
> Fix list indexof, remove and contains

- .github/workflows/include-deploy-release.yml
- .github/workflows/pr.yml
- CHANGELOG.md
- Fixes https://github.com/realm/realm-kotlin/issues/1690 
- Building cinterop-jvm Linux shared library in Release mode
> [RKOTLIN-1037] Copy missing JVM binaries (Win/Linux) when releasing

- packages/build.gradle.kts
API docs didn't publish with the correct styles. Fix inspired by https://github.com/realm/realm-swift/pull/8488/files#diff-4d2a8eefdf2a9783512a35da4dc7676a66404b6f3826a8af9aad038722da6823R1297
I did a manual push of the doc with this fix and it looks fine https://www.mongodb.com/docs/realm-sdks/kotlin/latest/index.html
> [RKOTLIN-1040] Fixing doc mime type

- CHANGELOG.md
- buildSrc/src/main/kotlin/Config.kt
- packages/cinterop/build.gradle.kts
Removes the fixed cmake version required by cinterop to rely on Cores cmake minimum version.
> [RKOTLIN-1062] Remove CMake required version

- .github/workflows/pr.yml
- CHANGELOG.md
- buildSrc/src/main/kotlin/Config.kt
- packages/cinterop/build.gradle.kts
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/Callback.kt
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/jvmMain/generic.Dockerfile
- packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/gradle-plugin/build.gradle.kts
- packages/jni-swig-stub/realm.i
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.h
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/log/RealmLog.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/QueryTests.kt
TODO:
Closes: #1682 
Closes: #1707
> [RKOTLIN-1031] Update to Core 14.4.1

- .github/workflows/include-deploy-release.yml
- .github/workflows/include-integration-tests.yml
- .github/workflows/pr.yml
- CHANGELOG.md
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/App.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/annotations/ExperimentalEdgeServerApi.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/AppImpl.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AppTests.kt
With this PR we add support for changing the App Services URL allowing roaming between Atlas and Edge server.
Closes https://github.com/realm/realm-kotlin/issues/1659
> [RKOTLIN-1023] Add support for changing App Services base URL

- .github/workflows/include-check-cache.yml
- CHANGELOG.md
- packages/library-base/src/commonMain/kotlin/io/realm/kotlin/exceptions/RealmException.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/exceptions/AppException.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/exceptions/SyncExceptions.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SubscriptionSetImpl.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/CredentialsTests.kt
closes https://github.com/realm/realm-kotlin/issues/1777
Removes a nullability check on the synchronization error message that is causing a null pointer exception crash
> [RKOTLIN-1102] Remove nullability check in `SubscriptionSetImpl.waitForSynchronization`

- CHANGELOG.md
- packages/cinterop/src/jvmMain/kotlin/io/realm/kotlin/jvm/SoLoader.kt
Fixes https://github.com/realm/realm-kotlin/issues/1715
This was tested locally by adding a JVM test that checks the schema version 
```Kotlin
assertEquals(realm.schemaVersion(), 42)
```
Then on AS edit the Core method `realm_get_schema_version` (inside https://github.com/realm/realm-core/blob/master/src/realm/object-store/c_api/schema.cpp#L52-L56) to return a different version which should compile a new native shared library to be extracted which has the new value. Observe that the test passes with the modified version .
Note: Obviously If you edit the `buildSrc/src/main/kotlin/Config.kt` to use a named version locally this work around won't work
> Always unpacking JVM native lib when using SNAPSHOT version

- CHANGELOG.md
- packages/cinterop/src/jvm/jni/utils.cpp
- packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
> [RKOTLIN-1089] Guard decoding issues when core logs invalid utf-8 messages

- .github/workflows/pr.yml
Update GHA scripts to build linux libraries with minimum glibc version 2.17.
It also disables AWS farm tests on non-releasable branches.
> Build linux libraries with glibc 2.17

- CHANGELOG.md
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/App.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/AppImpl.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AppTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/FunctionsTests.kt
This adds support for switching between logged in users with 
```
public interface App {
[....]
/**
* Switch current user.
*
* @param user the user that should be the new current user. The user must be one of the users
* that are already logged in.
* @throws IllegalStateException If the [user] is not logged in.
*/
public fun switchUser(user: User)
}
```
Closes #1813
> [RKOTLIN-1115] Add support for switching user

- .github/workflows/include-static-analysis.yml
- .github/workflows/pr.yml
- CHANGELOG.md
- packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
- packages/jni-swig-stub/realm.i
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/exceptions/SyncExceptions.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/AppConfigurationImpl.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/RealmSyncUtils.kt
- packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SyncSessionImpl.kt
- packages/library-sync/src/jvm/kotlin/io/realm/kotlin/mongodb/internal/OkHttpWebsocketClient.kt
- packages/test-base/src/androidMain/kotlin/io/realm/kotlin/test/platform/PlatformUtils.kt
- packages/test-base/src/commonMain/kotlin/io/realm/kotlin/test/platform/PlatformUtils.kt
- packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/EncryptionTests.kt
- packages/test-base/src/jvmMain/kotlin/io/realm/kotlin/test/platform/PlatformUtils.kt
- packages/test-base/src/nativeDarwin/kotlin/io/realm/kotlin/test/platform/PlatformUtils.kt
- packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/TestApp.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AppTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/FLXProgressListenerTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncClientResetIntegrationTests.kt
- packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncedRealmTests.kt
- packages/test-sync/src/jvmTest/kotlin/io/realm/kotlin/test/mongodb/jvm/PlatformNetworkingTests.kt
This PR includes the changes from the previous PR https://github.com/realm/realm-kotlin/pull/1801 as it ended up addressing some of the flaky tests from that. 
TODOs:
Closes #1811
> [RKOTLIN-1114] Fix sync client config not applied

- CHANGELOG.md
- README.md
- buildSrc/src/main/kotlin/Config.kt
- examples/min-android-sample/build.gradle.kts
- integration-tests/gradle/gradle72-test/build.gradle.kts
- integration-tests/gradle/gradle75-test/build.gradle.kts
- integration-tests/gradle/gradle8-test/build.gradle.kts
- integration-tests/gradle/gradle85-test/build.gradle.kts
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/IrUtils.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelLoweringExtension.kt
- packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/SyncLoweringExtension.kt
Fixes https://github.com/realm/realm-kotlin/issues/1825 via https://github.com/realm/realm-kotlin/pull/1826 
Credit @KitsuneAlex
> Fix compiler crash when using Kotlin 2.0.20 
