realm/realm-kotlin

README.md
Update once https://github.com/realm/realm-kotlin/issues/74 is merged
=> Update Readme with small API synopsis

packages/gradle-plugin/src/main/kotlin/io/realm/gradle/RealmAnalytics.kt
Just added default language to _please_ analytics pipeline
=> Add language to builder metric

Jenkinsfile, examples/kmm-sample/androidApp/src/main/java/io/realm/example/kmmsample/androidApp/MainActivity.kt, examples/kmm-sample/shared/src/commonMain/kotlin/io/realm/example/kmmsample/ExpressionRepository.kt, packages/cinterop/src/darwinCommon/kotlin/io/realm/interop/RealmInterop.kt, packages/cinterop/src/jvmCommon/kotlin/io/realm/interop/LongPointerWrapper.kt, packages/cinterop/src/jvmCommon/kotlin/io/realm/interop/NotificationCallback.kt, packages/cinterop/src/jvmCommon/kotlin/io/realm/interop/RealmInterop.kt, packages/jni-swig-stub/realm.i
=> Fix Android GC crash

README.md
Add badges to the README for where to find latest versions. See https://github.com/cmelchior/realm-kotlin/blob/master/README.md for how it will look.
=> Add Gradle Plugin Portal and Maven Central badges

CHANGELOG.md, examples/kmm-sample/androidApp/build.gradle.kts, examples/kmm-sample/shared/build.gradle.kts
=> Update changelog and bump core version

examples/kmm-sample/settings.gradle.kts, packages/cinterop/src/commonMain/kotlin/io/realm/interop/RealmInterop.kt, packages/cinterop/src/darwinCommon/kotlin/io/realm/interop/RealmInterop.kt, packages/cinterop/src/jvmCommon/kotlin/io/realm/interop/RealmInterop.kt, packages/library/src/commonMain/kotlin/io/realm/MutableRealm.kt, packages/library/src/commonMain/kotlin/io/realm/RealmObject.kt, test/src/androidTest/kotlin/io/realm/shared/RealmObjectTests.kt
Adding a few helper methods used by the #266. Just splitting it up into multiple PR's.
=> Add MutableRealm.isInTransaction() and RealmObject.isValid()

CHANGELOG.md, packages/cinterop/build.gradle.kts, packages/library/build.gradle.kts, packages/library/proguard-rules-consumer-common.pro, packages/plugin-compiler/src/main/kotlin/io/realm/compiler/RealmSchemaLoweringExtension.kt, packages/plugin-compiler/src/test/resources/schema/expected/00_ValidateIrBeforeLowering.ir
Also enabling Proguard/shrinker for Android
fixes https://github.com/realm/realm-kotlin/issues/293 and https://github.com/realm/realm-kotlin/issues/142
=> Support Release build type for Apple builds

CHANGELOG.md, packages/cinterop/src/commonMain/kotlin/io/realm/interop/RealmInterop.kt, packages/cinterop/src/darwinCommon/kotlin/io/realm/interop/RealmInterop.kt, packages/cinterop/src/jvmCommon/kotlin/io/realm/interop/RealmInterop.kt, packages/cinterop/src/nativeCommon/realm.def, packages/jni-swig-stub/realm.i, packages/library/src/commonMain/kotlin/io/realm/RealmList.kt, packages/library/src/commonMain/kotlin/io/realm/RealmObject.kt, packages/library/src/commonMain/kotlin/io/realm/internal/RealmObjectHelper.kt, packages/plugin-compiler/src/main/kotlin/io/realm/compiler/AccessorModifierIrGeneration.kt, packages/plugin-compiler/src/main/kotlin/io/realm/compiler/Identifiers.kt, packages/plugin-compiler/src/main/kotlin/io/realm/compiler/IrUtils.kt, packages/plugin-compiler/src/main/kotlin/io/realm/compiler/RealmModelSyntheticPropertiesGeneration.kt, packages/plugin-compiler/src/test/kotlin/io/realm/compiler/GenerationExtensionTest.kt, packages/plugin-compiler/src/test/resources/sample/expected/00_ValidateIrBeforeLowering.ir, packages/plugin-compiler/src/test/resources/sample/input/Sample.kt, test/src/androidTest/kotlin/io/realm/shared/RealmListTests.kt, test/src/commonMain/kotlin/io/realm/util/TypeDescriptor.kt, test/src/commonMain/kotlin/test/Sample.kt, test/src/commonMain/kotlin/test/list/RealmListContainer.kt, test/src/jvmTest/kotlin/io/realm/test/compiler/list/ListTests.kt, test/src/macosTest/kotlin/io/realm/shared/RealmListTests.kt
Contains the RealmList feature.
=> RealmList - story branch

packages/library/build.gradle.kts, tools/publish_release.sh
I uploaded the current version of the docs https://docs.mongodb.com/realm-sdks/kotlin/0.2.0/ and here https://docs.mongodb.com/realm-sdks/kotlin/latest/
=> Upload Dokka to S3 as part of release.

CHANGELOG.md, buildSrc/src/main/kotlin/Config.kt
Upgrade to Kotlin 1.5.20
Upgrade to latest Core commit
Upgrade Gradle Plugin Portal publishing plugin.
=> Upgrade to Kotlin 1.5.20

README.md
Update description of SNAPSHOTs from JFrog to Maven Central
=> Update SNAPSHOT description

buildSrc/build.gradle.kts, packages/build.gradle.kts, packages/settings.gradle.kts, test/build.gradle.kts, test/settings.gradle.kts
Remove the `kotlin-dev` Bintray repository as it is no longer needed and it was slowing down the gradle sync.
=> Remove kotlin-dev bintray repository

CHANGELOG.md, packages/plugin-compiler/src/main/kotlin/io/realm/compiler/AccessorModifierIrGeneration.kt, packages/plugin-compiler/src/test/resources/sample/expected/00_ValidateIrBeforeLowering.ir, test/src/androidTest/kotlin/io/realm/shared/SampleTests.kt, test/src/commonMain/kotlin/test/Sample.kt
=> Setting accessor origin to prevent optimizations

CHANGELOG.md, README.md, examples/kmm-sample/shared/src/commonMain/kotlin/io/realm/example/kmmsample/ExpressionRepository.kt, packages/library/src/commonMain/kotlin/io/realm/RealmConfiguration.kt, packages/plugin-compiler/src/main/kotlin/io/realm/compiler/Identifiers.kt, packages/plugin-compiler/src/main/kotlin/io/realm/compiler/RealmSchemaLoweringExtension.kt, packages/plugin-compiler/src/test/resources/schema/input/Schema.kt, test/src/androidTest/kotlin/io/realm/InstrumentedTests.kt, test/src/androidTest/kotlin/io/realm/MemoryTests.kt, test/src/androidTest/kotlin/io/realm/RealmTests.kt, test/src/androidTest/kotlin/io/realm/shared/ImportTests.kt, test/src/androidTest/kotlin/io/realm/shared/LinkTests.kt, test/src/androidTest/kotlin/io/realm/shared/MigrationTests.kt, test/src/androidTest/kotlin/io/realm/shared/MutableRealmTests.kt, test/src/androidTest/kotlin/io/realm/shared/NullabilityTests.kt, test/src/androidTest/kotlin/io/realm/shared/RealmConfigurationTests.kt, test/src/androidTest/kotlin/io/realm/shared/RealmListTests.kt, test/src/androidTest/kotlin/io/realm/shared/RealmObjectTests.kt, test/src/androidTest/kotlin/io/realm/shared/RealmResultsTests.kt, test/src/androidTest/kotlin/io/realm/shared/SampleTests.kt, test/src/androidTest/kotlin/io/realm/shared/SchemaTests.kt, test/src/androidTest/kotlin/io/realm/shared/notifications/RealmListNotificationsTests.kt, test/src/androidTest/kotlin/io/realm/shared/notifications/RealmNotificationsTests.kt, test/src/androidTest/kotlin/io/realm/shared/notifications/RealmObjectNotificationsTests.kt, test/src/androidTest/kotlin/io/realm/shared/notifications/RealmResultsNotificationsTests.kt, test/src/androidTest/kotlin/io/realm/shared/notifications/SystemNotificationTests.kt, test/src/jvmTest/kotlin/io/realm/test/compiler/PrimaryKeyTests.kt, test/src/macosTest/kotlin/io/realm/InstrumentedTests.kt, test/src/macosTest/kotlin/io/realm/MemoryTests.kt
Renaming to accommodate discussion in https://github.com/realm/realm-kotlin/pull/395#discussion_r701968223
=> Renaming default configuration factory method

packages/library-sync/src/commonMain/kotlin/io/realm/mongodb/App.kt, test/sync/src/androidTest/kotlin/io/realm/test/mongodb/shared/AppTests.kt
Little helper function that avoids the annoying overhead of creating a Builder. We have a similar method in Realm Java.
=> Add easy way to create App without needing to create a Builder.

CHANGELOG.md, Jenkinsfile, packages/cinterop/build.gradle.kts, packages/cinterop/src/jvm/jni/env_utils.cpp, packages/cinterop/src/jvmMain/linux/CMakeLists.txt, packages/cinterop/src/jvmMain/linux/generic.Dockerfile, packages/cinterop/src/jvmMain/windows/CMakeLists.txt, packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
Add support for Linux (x86_64 Centos 7 and up) and Windows (x86_64 Wi…n 8.1 and up) for JVM targets
=> JVM support Linux & Windows targets

CHANGELOG.md, Jenkinsfile, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Config.kt, buildSrc/src/main/kotlin/realm-lint.gradle.kts, examples/min-android-sample/build.gradle.kts, packages/cinterop/src/jvm/kotlin/io/realm/internal/interop/PropertyFlag.kt, packages/gradle-plugin/src/main/kotlin/io/realm/gradle/RealmPlugin.kt, test/base/build.gradle.kts, test/sync/build.gradle.kts
Update to Kotlin 1.6.0 + update a few other dependencies.
=> Update to Kotlin 1.6.0.

CHANGELOG.md, buildSrc/src/main/kotlin/Config.kt
Update to AGP 7.1.0-beta05.
Update to AtomicFu 0.17.0.
Update to Dokka 1.6.0.
This should also unblock https://github.com/realm/realm-kotlin/issues/558
=> Update to Kotlin 1.6.10

CHANGELOG.md, buildSrc/src/main/kotlin/Config.kt, examples/kmm-sample/gradle/wrapper/gradle-wrapper.properties, gradle/wrapper/gradle-wrapper.properties, packages/gradle/wrapper/gradle-wrapper.properties, test/gradle/wrapper/gradle-wrapper.properties
Plus a few other minor test dependencies.
=> Update Gradle to 7.3.3 and AGP to 7.1.0-rc01.

CHANGELOG.md, Jenkinsfile, packages/cinterop/build.gradle.kts, packages/cinterop/src/jvmMain/kotlin/io/realm/jvm/SoLoader.kt, packages/jni-swig-stub/realm.i
Build macos JVM dylib on an M1 node
=> Support JVM on M1

Jenkinsfile
Fixes https://github.com/realm/realm-kotlin/issues/631
=> Removed system key events from monkey runner

packages/library-base/build.gradle.kts, packages/library-sync/build.gradle.kts
(From "Kotlin Multiplatform SDK")
=> Change Dokka Project title to "Kotlin SDK"

README.md, packages/library-base/src/commonMain/kotlin/io/realm/notifications/ListChange.kt, packages/library-base/src/commonMain/kotlin/io/realm/notifications/ObjectChange.kt, packages/library-base/src/commonMain/kotlin/io/realm/notifications/RealmChange.kt, packages/library-base/src/commonMain/kotlin/io/realm/notifications/ResultsChange.kt, test/base/src/androidTest/kotlin/io/realm/test/shared/ReadMeTests.kt
Fixes some wrong references and unifies the style. It also adds to the readme some examples on notifications.
=> Fix fine grained notification doc examples

CHANGELOG.md, packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmUtils.kt, test/base/src/androidTest/kotlin/io/realm/test/shared/MutableRealmTests.kt
=> Allow update of existing objects in lists with UpdatePolicy.ALL

README.md
Fixed a small typo in the comment and code snippet
=> Fixed a typo in Readme.md

CHANGELOG.md, packages/library-base/src/commonMain/kotlin/io/realm/internal/Converters.kt, packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmListInternal.kt, packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmObjectHelper.kt, test/base/src/androidTest/kotlin/io/realm/test/shared/RealmListTests.kt
=> Fix list notifications operation on the wrong realm reference

CHANGELOG.md, packages/cinterop/src/darwin/kotlin/io/realm/internal/interop/RealmInterop.kt
=> Added `@SharedImmutable` annotation to freeze values

README.md
=> Add compatible Kotlin version

CHANGELOG.md, packages/jni-swig-stub/realm.i
Fixing Swig multi argument typemaps so that they match arguments according to latest core updates.
=> Upgrade to latest core

packages/library-sync/overview.md, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/App.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/AppConfiguration.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/AuthenticationProvider.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/Credentials.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/User.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/sync/SyncConfiguration.kt, test/sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/util/AdminApi.kt
Adjust to new product naming on Atlas.
=> Adjust documentation to new product naming

CHANGELOG.md, README.md, buildSrc/src/main/kotlin/Config.kt
You can see the new README here: https://github.com/realm/realm-kotlin/tree/cm/docs-1.0.0
=> Prepare release docs

packages/gradle-plugin/src/main/kotlin/io/realm/kotlin/gradle/analytics/AnalyticsService.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/BaseRealm.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/Configuration.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/MutableRealm.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/Realm.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/dynamic/DynamicRealmObject.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/log/LogLevel.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/log/RealmLogger.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/migration/RealmMigration.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/query/RealmResults.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/AuthenticationProvider.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/Credentials.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/User.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/exceptions/ServiceExceptions.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/exceptions/SyncExceptions.kt
Fixed see notations for external http links, removed dead internal links plus some formatting. Nothing serious.
=> Dokka walkthrough for dead links, outdated stuff, etc.

CHANGELOG.md, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SyncConfigurationImpl.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/sync/PartitionValue.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/sync/SyncConfiguration.kt
=> Support ObjectId as a partition key

Jenkinsfile
See https://mongodb.slack.com/archives/CTU01HNCV/p1653065024501769?thread_ts=1652953089.189209&cid=CTU01HNCV
=> Fix credentials used for uploading release metadata

CHANGELOG.md, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/Configuration.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmObjectUtil.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/sync/PartitionValue.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/sync/SyncConfiguration.kt, test/sync/src/androidTest/kotlin/io/realm/kotlin/test/SyncClientResetIntegrationJVMTests.kt, test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/FlexibleSyncIntegrationTests.kt, test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/MutableSubscriptionSetTests.kt, test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SubscriptionSetTests.kt, test/sync/src/androidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SyncConfigTests.kt, test/sync/src/commonMain/kotlin/io/realm/kotlin/entities/sync/flx/FlexEmbeddedObject.kt, test/sync/src/commonTest/kotlin/io/realm/kotlin.test/Utils.kt, tools/sync_test_server/app_template/services/BackingDB/rules/test_data.FlexParentObject.json
Fixes #https://github.com/realm/realm-kotlin/issues/945
=> Allow Embedded Objects to be added to Sync schemas

.github/workflows/auto-merge-release-to-master.yml
This will automatically create PR's between branches we think should be in sync:
- `releases` -> `master`
- `master` -> `release/ktor2-support`
=> Enable auto-merge between branches

packages/test-sync/src/androidTest/kotlin/io/realm/kotlin/test/shared/SyncedRealmTests.kt
Closes https://github.com/realm/realm-kotlin/issues/1051
Before this PR, it was possible for the writes on Realm 2 and 3 to happen at the same "time". Which would result in Realm one seeing two writes in the same notification. Which would break the test.
I rewrote the logic to test for the value after each step.
=> Remove race conditions in tests.

CHANGELOG.md, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/LiveRealm.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmImpl.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/SuspendableNotifier.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/SuspendableWriter.kt, packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/MemoryTests.kt
=> Break reference cycles to realm from realm callbacks

CHANGELOG.md, packages/cinterop/src/darwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/Converters.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmListInternal.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmObjectHelper.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmSetInternal.kt, packages/test-base/src/androidTest/kotlin/io/realm/kotlin/test/shared/QueryTests.kt
=> Fix using object references as query argument

CHANGELOG.md
Pulling in https://github.com/realm/realm-core/pull/5999/files in order to fix some performance issues downloading very large server side Realms
=> Update to latest Core commit

CONTRIBUTING.md, tools/sync_test_server/start_local_server.sh, tools/sync_test_server/start_server.sh
Makes set-up files a bit more detailed in order to improve and accelerate the onboarding for new members.
=> Clarify and add instructions to set-up files.

CHANGELOG.md, packages/cinterop/src/androidAndroidTest/kotlin/io/realm/kotlin/test/CinteropTest.kt, packages/cinterop/src/nativeDarwinTest/kotlin/io/realm/kotlin/test/CinteropTest.kt, packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SyncSessionTests.kt
Also fixed a test that was causing timeouts due to a race condition.
=> Update to core 12.12.0

.github/workflows/pr.yml, packages/build.gradle.kts, packages/cinterop/build.gradle.kts, packages/jni-swig-stub/build.gradle.kts, packages/test-base/build.gradle.kts, packages/test-sync/build.gradle.kts
Fixes build issues after merging `master` into `feature/github-actions`
=> Fix GHA build

CHANGELOG.md, packages/cinterop/build.gradle.kts, packages/library-base/build.gradle.kts, packages/library-base/proguard-rules-consumer-common.pro, packages/library-sync/build.gradle.kts, packages/test-base/build.gradle.kts, packages/test-sync/build.gradle.kts
=> Only publish release variants

packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/util/AppServicesClient.kt, packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/util/KtorTestMethods.kt, packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/util/TestAppInitializer.kt
Rebased https://github.com/realm/realm-kotlin/pull/1177 onto `releases`
=> Remove forward-as-patch workaround

CHANGELOG.md, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmImpl.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/SuspendableNotifier.kt, packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/notifications/RealmNotificationsTests.kt, packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SyncedRealmTests.kt
=> Fix missing realm flow-events from remote updates on synced realms

.gitignore, CHANGELOG.md, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/org/jetbrains/kotlin/gradle/internal/testing/TCServiceMessagesClient.kt, buildSrc/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/jvm/tasks/KotlinJvmTest.kt
This applies the workaround mentioned in https://youtrack.jetbrains.com/issue/KT-54634
=> Workaround for test runner issues with Gradle 7.6

CHANGELOG.md, integration-tests/gradle-plugin-test/single-platform/src/main/java/io/realm/test/singleplatform/model/Pojo.java, packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelSyntheticPropertiesGeneration.kt, packages/plugin-compiler/src/test/resources/sample/expected/01_AFTER.ValidateIrBeforeLowering.ir, packages/plugin-compiler/src/test/resources/schema/expected/01_AFTER.ValidateIrBeforeLowering.ir
=> Add missing generic type parameter for generated property

packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/notifications/RealmNotificationsTests.kt
This reworks the assertion in `RealmNotificationTests.cancelAsFlow` about not delivering any notifications in a cancelled scope.
=> Fix faulty RealmNotificationTests.cancelAsFlow test

CHANGELOG.md, packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt, packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt, packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/AppConfiguration.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/AppConfigurationImpl.kt, packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/AppConfigurationTests.kt, packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SyncedRealmTests.kt, packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/internal/SyncConnectionParamsTests.kt
Closes https://github.com/realm/realm-kotlin/issues/407
=> Add support for AppConfiguration.appName and .appVersion

CHANGELOG.md, packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelSyntheticPropertiesGeneration.kt, packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/PersistedNameTests.kt
=> Fix compiler error for duplicate persisted names.

CHANGELOG.md, dependencies.list, packages/cinterop/src/androidAndroidTest/kotlin/io/realm/kotlin/test/CinteropTest.kt, packages/cinterop/src/nativeDarwinTest/kotlin/io/realm/kotlin/test/CinteropTest.kt, packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SubscriptionSetTests.kt, packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/util/AppServicesClient.kt, packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/util/TestAppInitializer.kt
Closes #1285 
Including updating to the latest BAAS test server.
=> Update Core to 13.4.2.

README.md
Closes https://github.com/realm/realm-kotlin/issues/1237
You can see the README here https://github.com/realm/realm-kotlin/tree/cm/version-matrix#version-compatibility-matrix
=> Add version compatibility matrix to the README.

CHANGELOG.md, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/SuspendableWriter.kt, packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/MutableRealmTests.kt, packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/RealmTests.kt
=> Allow returning invalid objects from writes

CHANGELOG.md, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/UserImpl.kt
=> Return correct provider for JWT-authenticated users

packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/VersionTrackingTests.kt
=> Fix flaky VersionTrackingTests

CHANGELOG.md, packages/cinterop/src/androidAndroidTest/kotlin/io/realm/kotlin/test/CinteropTest.kt, packages/cinterop/src/nativeDarwinTest/kotlin/io/realm/kotlin/test/CinteropTest.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/Configuration.kt, packages/library-base/src/commonMain/kotlin/io/realm/kotlin/log/RealmLog.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/AppConfiguration.kt, packages/test-base/src/androidAndroidTest/kotlin/io/realm/kotlin/test/shared/RealmConfigurationTests.kt, packages/test-sync/src/androidAndroidTest/kotlin/io/realm/kotlin/test/mongodb/shared/SyncClientResetIntegrationTests.kt, packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/TestApp.kt
=> Update to Core 13.9.3

CHANGELOG.md, README.md
Update version list in the README and remove release from CHANGELOG that was never released.
=> Cleanup README and CHANGELOG

packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt, packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt, packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/AppConfigurationImpl.kt
See https://github.com/realm/realm-core/issues/6656. Hopefully this should be enough to prevent crashes until a fix can be found.
No changelog as no release has been made with this yet.
=> Disable multiplexing

CHANGELOG.md, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/AppConfiguration.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/AppConfigurationImpl.kt, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/HttpClientCache.kt, packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AppConfigurationTests.kt
Adds support for custom request headers and custom authorization name, required for proxy setups.
=> Add Proxy support with custom request headers and custom authorization name

dependencies.list, packages/test-base/src/commonMain/kotlin/io/realm/kotlin/test/util/Utils.kt, packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/FlexibleSyncIntegrationTests.kt, packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/FunctionsTests.kt, packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SubscriptionSetTests.kt
+ update some tests to reflect the changes.
Also bumping the test timeout for various tests preparing for GitHub Actions which seems to be quite a bit slower on some of these tests.
=> Update BAAS test server version

buildSrc/src/main/kotlin/Config.kt
See https://github.com/JetBrains/kotlin/releases/tag/v1.9.20-Beta
=> Test with Kotlin 1.9.20-Beta

CHANGELOG.md, packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/AppConfiguration.kt, packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AppConfigurationTests.kt
Fixes https://github.com/realm/realm-kotlin/issues/1685
=> RKOTLIN-1033: Update default base url
